"""The three names this project deliberately does NOT share — asserted
against a built wheel, not against pyproject.toml.

PyPI's `rite` belongs to an unrelated, actively-maintained package (Scape
Agency's "Rite - Python Utility Package"). It is not dormant, so PEP 541
offers no route to the name — and it collides on all three axes at once: it
publishes the distribution `rite`, ships a `rite` console script, and owns
the top-level import name `rite`.

So this project splits them:

    distribution     rite-ai      (what a package manager installs)
    import package   rite_ai      (what `import` resolves)
    commands         rite         (primary - the project's actual name)
                     rite-ai      (alias, for a PATH that already has a `rite`)

The import-package split is the load-bearing one and was decided by
measurement. With the import name left as `rite`, installing both projects
into one non-isolated environment merges the two `rite/` trees file by file
with no warning from pip or uv. The observed result was `rite-ai --version`
printing `rite, version 0.2.4` — our CLI module loading against their
`__init__`. The alias command did NOT escape the collision, because the
collision was never in the command name.

WHY THIS FILE BUILDS A WHEEL. An earlier version of it read pyproject.toml
and asserted on dict keys, which checks that the DECLARATION is right, not
that the artifact is. That is the same blind spot as the bug it was written
to guard: `rite init` crashed with FileNotFoundError under `pipx install` /
`uv tool install` while 560 tests passed green from the source tree, because
`templates/` was never packaged. A declaration assert would have gone green
on a wheel that was still broken in some other way.

Worse, file-presence was never the real defect — path RESOLUTION was.
`templates_dir()` has two branches, and the suite exercised exactly one:
instrumenting it across the full suite gave 28 hits on the walk-up branch
and zero on the fallback, which is the branch every real (non-editable)
install takes. So the wheel here is not merely inspected for files; the
resolution function is driven against the extracted tree, through the branch
no other test reaches. Credit to the review that caught this.

The build costs about a third of a second, which is cheap enough not to hide
behind a marker — a guard nobody runs is not a guard.
"""

from __future__ import annotations

import shutil
import subprocess
import zipfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent


@pytest.fixture(scope="session")
def wheel_dir(tmp_path_factory) -> Path:
    """The extracted contents of a freshly built wheel."""
    if shutil.which("uv") is None:
        pytest.skip("needs `uv` on PATH to build the wheel these assert on")
    out = tmp_path_factory.mktemp("wheel-build")
    proc = subprocess.run(
        ["uv", "build", "--wheel", "--out-dir", str(out)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=300,
    )
    if proc.returncode != 0:
        pytest.fail(f"wheel build failed:\n{proc.stdout}\n{proc.stderr}")
    wheels = list(out.glob("*.whl"))
    assert len(wheels) == 1, f"expected exactly one wheel, got {wheels}"
    extracted = out / "extracted"
    with zipfile.ZipFile(wheels[0]) as zf:
        zf.extractall(extracted)
    return extracted


def _dist_info(wheel_dir: Path) -> Path:
    matches = list(wheel_dir.glob("*.dist-info"))
    assert len(matches) == 1, f"expected one .dist-info, got {matches}"
    return matches[0]


def test_wheel_is_the_rite_ai_distribution(wheel_dir):
    metadata = (_dist_info(wheel_dir) / "METADATA").read_text()
    assert "\nName: rite-ai\n" in metadata


def test_wheel_ships_both_commands_on_one_entry_point(wheel_dir):
    """Both are real console scripts generated by the build backend — not a
    shim forwarding to the other — so neither breaks if the other is removed
    and they cannot drift into being different programs."""
    entry_points = (_dist_info(wheel_dir) / "entry_points.txt").read_text()
    scripts = dict(
        line.split(" = ", 1) for line in entry_points.splitlines() if " = " in line
    )
    assert scripts == {
        "rite": "rite_ai.cli.main:cli",
        "rite-ai": "rite_ai.cli.main:cli",
    }


def test_wheel_ships_rite_ai_and_no_colliding_rite_package(wheel_dir):
    """The regression guard for the rename itself. A revert to
    `packages = ["src/rite"]` would put a top-level `rite/` back in the
    wheel and re-arm the silent two-project merge."""
    assert (wheel_dir / "rite_ai" / "__init__.py").is_file()
    assert (wheel_dir / "rite_ai" / "VERSION").is_file()
    assert not (wheel_dir / "rite").exists()


def test_wheel_ships_every_template_the_source_tree_has(wheel_dir):
    """`templates/` lives outside the package directory, so it ships only
    because of an explicit force-include — the failure mode that broke
    `rite init` for every real install. Compared against the source tree so
    that ADDING a template without packaging it fails here too."""
    source = {
        p.relative_to(REPO_ROOT / "templates")
        for p in (REPO_ROOT / "templates").rglob("*")
        if p.is_file()
    }
    shipped = {
        p.relative_to(wheel_dir / "rite_ai" / "templates")
        for p in (wheel_dir / "rite_ai" / "templates").rglob("*")
        if p.is_file()
    }
    assert source, "no templates found in the source tree — test is not testing"
    assert shipped == source


def test_templates_dir_finds_them_in_the_installed_layout(wheel_dir, monkeypatch):
    """The branch no other test reaches.

    `templates_dir()` walks up looking for a `templates/` sitting next to a
    `pyproject.toml`; that succeeds only in a source checkout. Every real
    install falls through to the second branch. Pointing the module's
    `__file__` at the paths.py inside the EXTRACTED WHEEL reproduces the
    installed layout exactly — real files, real directory shape — instead of
    asserting that a config key is spelled correctly.

    Resolving to a path inside the wheel is itself the proof that the
    fallback ran: the walk-up branch could only ever have returned this
    repo's own `templates/`."""
    from rite_ai.cli.init import paths

    installed_paths_py = wheel_dir / "rite_ai" / "cli" / "init" / "paths.py"
    assert installed_paths_py.is_file()
    monkeypatch.setattr(paths, "__file__", str(installed_paths_py))

    resolved = paths.templates_dir()

    assert resolved == wheel_dir / "rite_ai" / "templates"
    assert (resolved / "review-checklist.md").is_file()


def test_templates_dir_prefers_a_source_checkout_when_there_is_one(monkeypatch):
    """The other branch, stated explicitly rather than relied on implicitly
    by the ~28 tests that happen to hit it."""
    from rite_ai.cli.init import paths

    assert paths.templates_dir() == REPO_ROOT / "templates"


def test_import_package_is_importable_under_its_real_name():
    import rite_ai

    assert rite_ai.__version__
