"""The friction audit's closed findings, as one walk of one project.

Each of these has unit coverage already; what did not exist was a check
that they are all still true TOGETHER, in a project generated by today's
code — which is the only form the audit's claims are actually made in.
The table was last verified by hand at `7674096`, and by the time anyone
asked again it had moved a long way, with no way to answer except
re-deriving it. Now `pytest` answers it.

Each test cites the audit item it holds. If one fails, the audit's status
table is wrong, not this file.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest
from click.testing import CliRunner

import rite_ai.sandbox as sb
from rite_ai.cli.init import run_init
from rite_ai.cli.main import cli


@pytest.fixture(scope="module")
def a_generated_project(tmp_path_factory) -> Path:
    root = tmp_path_factory.mktemp("audit") / "acme"
    root.mkdir()
    (root / "pyproject.toml").write_text(
        '[project]\nname = "acme"\ndescription = "Invoicing."\n'
    )
    subprocess.run(["git", "init", "-q", str(root)], check=True)
    original = sb.platform_can_sandbox
    sb.platform_can_sandbox = lambda: False
    try:
        cwd = Path.cwd()
        import os

        os.chdir(root)
        assert run_init(root, yes=True).status == "created"
        assert CliRunner().invoke(cli, ["add", "worker", "alpha"]).exit_code == 0
        os.chdir(cwd)
    finally:
        sb.platform_can_sandbox = original
    return root


def _in(root: Path, monkeypatch, args: list[str]):
    monkeypatch.chdir(root)
    with patch("keyring.get_password", return_value=None):
        return CliRunner().invoke(cli, args)


def test_item_1_doctor_names_the_build_it_is_running(a_generated_project, monkeypatch):
    """Audit #1: the one-liner installed the pre-fix tool and nothing said
    which build was answering."""
    out = _in(a_generated_project, monkeypatch, ["doctor"]).output

    assert "rite " in out
    # The three forms doctor reports: a tag+commit for an installed build, or
    # a dev/editable checkout with its path.
    assert any(
        marker in out for marker in ("installed from", "dev checkout", "editable")
    ), out.splitlines()[:3]


def test_item_2_a_typo_in_a_hand_edited_file_is_refused(
    a_generated_project, monkeypatch
):
    """Audit #2: typos in the files a person hand-edits used to vanish."""
    from rite_ai.config.parse import parse_brief

    brief = a_generated_project / ".rite" / "brief.yaml"
    original = brief.read_text()
    brief.write_text(original + "\nnmae: acme\n")
    try:
        problem = parse_brief(brief)
        assert hasattr(problem, "message"), "an unknown key was accepted"
        assert "nmae" in problem.message
    finally:
        brief.write_text(original)


def test_item_3_an_exported_api_key_is_reported_and_never_printed(
    a_generated_project, monkeypatch
):
    """Audit #3: per-token billing was inherited silently."""
    monkeypatch.setenv("ANTHROPIC_API_KEY", "sk-ant-not-a-real-key")

    out = _in(a_generated_project, monkeypatch, ["doctor"]).output

    assert "ANTHROPIC_API_KEY" in out
    assert "sk-ant-not-a-real-key" not in out, "doctor printed the key itself"


def test_item_4_a_board_with_no_key_names_the_command_that_fixes_it(
    a_generated_project, monkeypatch
):
    """Audit #4: `projects: {}` was written and the fix pointed at nowhere."""
    out = _in(a_generated_project, monkeypatch, ["board", "list"]).output

    assert "credential set" in out or "ticket_backend" in out, out


def test_item_5_a_worker_nobody_started_is_not_a_stall(
    a_generated_project, monkeypatch
):
    """Audit #5: it read as dead."""
    status = _in(a_generated_project, monkeypatch, ["status"]).output
    watchdog = _in(a_generated_project, monkeypatch, ["watchdog"])

    assert "not started" in status.lower(), status
    assert watchdog.exit_code == 0, watchdog.output


def test_item_6_a_yes_run_says_what_it_decided(tmp_path, monkeypatch):
    """Audit #6: `--yes` decided without saying so."""
    root = tmp_path / "fresh"
    root.mkdir()
    subprocess.run(["git", "init", "-q", str(root)], check=True)
    monkeypatch.setattr(sb, "platform_can_sandbox", lambda: False)
    monkeypatch.chdir(root)

    import contextlib
    import io

    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        run_init(root, yes=True)

    out = buffer.getvalue()
    assert "Resolved without asking" in out
    assert "operations.ticket_backend" in out
