"""The invariant under S13 and the `--yes` gap, over the whole case range.

S11's fix was tested at two extremes, a byte-empty directory and a repository
with code, and every mutation of it flipped the same predicate between them.
The directories people actually have sit in the middle: the setup's own
`install.sh` in the root, a prior init's CLAUDE.md, code that is in no
repository, a repository with nothing committed. And a bare `rite init --yes`
reached no module check at all. So this crosses every route with every kind
of directory and holds four properties on each, from the CLI and the files
init writes alone (it imports nothing init-internal, so it runs unchanged
against an older rite):

1. **Told.** If no module is registered, the output says so.
2. **Asked.** If no module is registered and someone is there, they were asked
   where the code is.
3. **No false claim.** "will be taken from what's there" is printed only for a
   directory with something of the project's in it.
4. **Not "Ready."** "Ready. Start a Dispatch session" is never printed for a
   project with no module.
"""

from __future__ import annotations

import itertools
import re
import subprocess
from pathlib import Path

import pytest
import yaml
from click.testing import CliRunner

import rite_ai.sandbox as sb
from rite_ai.cli.main import cli

CLAIM = "will be taken\nfrom what's there"
TOLD = re.compile(r"No module (is|would be) registered")
ASKED = ("Where is the code?", "No repositories found. Add a module?")
READY = "Ready. Start a Dispatch session"

RITE_INSTALLER = "#!/bin/sh\n# rite installer.\n#\n# All three end at the same place.\n"
GENERATED_CLAUDE_MD = (
    "# CLAUDE.md\n\nGenerated by `rite init`. Edit the sections below.\n"
)


@pytest.fixture(autouse=True)
def _isolated(monkeypatch):
    monkeypatch.setattr(sb, "platform_can_sandbox", lambda: False)


def _git(cwd: Path, *args: str) -> None:
    subprocess.run(
        ["git", "-c", "user.email=a@b", "-c", "user.name=t", *args],
        cwd=cwd,
        check=True,
        capture_output=True,
    )


# --- the directories people have, from nothing to a real repository -----------


def _empty(d: Path) -> None:
    pass


def _rite_installer(d: Path) -> None:
    (d / "install.sh").write_text(RITE_INSTALLER)


def _prior_init_leftovers(d: Path) -> None:
    (d / "CLAUDE.md").write_text(GENERATED_CLAUDE_MD)
    (d / ".claude").mkdir()
    (d / ".claude" / "settings.json").write_text("{}\n")
    _rite_installer(d)


def _a_readme(d: Path) -> None:
    (d / "README.md").write_text("# yoloAI\n")


def _code_in_no_repository(d: Path) -> None:
    (d / "main.go").write_text("package main\n")


def _someone_elses_install_sh(d: Path) -> None:
    (d / "install.sh").write_text("#!/bin/sh\nmake install\n")


def _a_repository_with_nothing_committed(d: Path) -> None:
    _git(d, "init", "-q", "-b", "main")
    (d / "main.go").write_text("package main\n")


def _a_repository_with_a_commit(d: Path) -> None:
    _a_repository_with_nothing_committed(d)
    _git(d, "add", "-A")
    _git(d, "commit", "-qm", "code")


CONTENTS = {
    "empty": (_empty, False),
    "rite-installer": (_rite_installer, False),
    "prior-init-leftovers": (_prior_init_leftovers, False),
    "a-readme": (_a_readme, True),
    "code-in-no-repository": (_code_in_no_repository, True),
    "someone-elses-install.sh": (_someone_elses_install_sh, True),
    "repository-nothing-committed": (_a_repository_with_nothing_committed, True),
    "repository-with-a-commit": (_a_repository_with_a_commit, True),
}
"""name -> (make it, whether the project has anything of its own there)."""

BLANKS = "\n" * 30

ROUTES = {
    # From scratch, every question left at its default ("3" is no board).
    "scratch": (lambda _t: [], True, "n\n" + "\n" * 10 + "3\n" + BLANKS),
    # Existing spec or code, path ".", every question left at its default.
    "existing-code": (lambda _t: [], True, "y\n" + BLANKS),
    # Nobody there, no preset: the path that reached no module check.
    "yes": (lambda _t: ["--yes"], False, None),
    # Nobody there, a preset naming the path (#150's one --yes shape).
    "yes-with-source": (
        lambda t: ["--yes", "--config", str(_preset(t))],
        False,
        None,
    ),
}


def _preset(tmp_path: Path) -> Path:
    p = tmp_path / "preset.yaml"
    p.write_text("source:\n  path: .\n")
    return p


def _run(tmp_path: Path, route: str, content: str):
    make, has_content = CONTENTS[content]
    args_for, interactive, answers = ROUTES[route]
    root = tmp_path / "yoloAI"
    root.mkdir()
    make(root)
    result = CliRunner().invoke(
        cli, ["init", *args_for(tmp_path), str(root)], input=answers
    )
    assert result.exit_code == 0, result.output
    modules = yaml.safe_load((root / ".rite" / "modules.yaml").read_text())
    return result.output, bool(modules.get("modules")), interactive, has_content


CASES = list(itertools.product(ROUTES, CONTENTS))


@pytest.mark.parametrize("route,content", CASES)
def test_1_no_module_is_told(tmp_path: Path, route: str, content: str):
    out, registered, _, _ = _run(tmp_path, route, content)
    if not registered:
        assert TOLD.search(out), f"not told there is no module:\n{out}"


@pytest.mark.parametrize("route,content", CASES)
def test_2_no_module_is_asked_about(tmp_path: Path, route: str, content: str):
    out, registered, interactive, _ = _run(tmp_path, route, content)
    if not registered and interactive:
        assert any(a in out for a in ASKED), f"never asked where the code is:\n{out}"


@pytest.mark.parametrize("route,content", CASES)
def test_3_no_claim_to_read_what_is_not_there(tmp_path: Path, route: str, content: str):
    out, _, _, has_content = _run(tmp_path, route, content)
    if CLAIM in out:
        assert has_content, f"claimed to read what is not there:\n{out}"


@pytest.mark.parametrize("route,content", CASES)
def test_4_no_module_is_never_ready(tmp_path: Path, route: str, content: str):
    out, registered, _, _ = _run(tmp_path, route, content)
    if not registered:
        assert READY not in out, f"said Ready with no module:\n{out}"
