"""What `rite init` leaves a project with: S13, S21, S20 and S18.

`test_init_never_leaves_no_module_unsaid.py` holds the zero-module invariant
across every route and directory. This file pins the pieces:

* S13: what counts as the project's own content, and what is rite's leftover;
* S21: a fresh project's schedule is a stated default, never empty and never
  silent; `--config` sets it; an existing project's is untouched;
* S20: init offers a Worker once there is a module;
* S18: a re-init offers back the namespace that still holds this repository's
  credentials, matched by the module's remote, and only then.

Real git and the real CLI; the keychain is not touched (the registry that
lists stored accounts is written directly, in a per-test `RITE_HOME_DIR`).
"""

from __future__ import annotations

import itertools
import json
import shutil
import subprocess
import time
from datetime import datetime
from pathlib import Path

import pytest
import yaml
from click.testing import CliRunner

import rite_ai.sandbox as sb
from rite_ai.cli.init.detect import content_entries
from rite_ai.cli.init.questionnaire import holds_nothing
from rite_ai.cli.main import cli
from rite_ai.config.parse import parse_config
from rite_ai.credentials import store
from rite_ai.schedule import machine_zone_name, workers_at

RITE_INSTALLER = "#!/bin/sh\n# rite installer.\n"
GENERATED_CLAUDE_MD = "# CLAUDE.md\n\nGenerated by `rite init`. Edit below.\n"


@pytest.fixture(autouse=True)
def _isolated(monkeypatch, tmp_path):
    monkeypatch.setattr(sb, "platform_can_sandbox", lambda: False)
    monkeypatch.setenv("RITE_HOME_DIR", str(tmp_path / "rite-home"))


def _git(cwd: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-c", "user.email=a@b", "-c", "user.name=t", *args],
        cwd=cwd,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def _repo(root: Path, origin: str | None = None) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    _git(root, "init", "-q", "-b", "main")
    (root / "main.go").write_text("package main\n")
    _git(root, "add", "-A")
    _git(root, "commit", "-qm", "code")
    if origin:
        _git(root, "remote", "add", "origin", origin)
    return root


def _init(root: Path, *args: str, input: str | None = None) -> str:
    result = CliRunner().invoke(cli, ["init", *args, str(root)], input=input)
    assert result.exit_code == 0, result.output
    return result.output


def _config(root: Path):
    return parse_config(root / ".rite" / "config.yaml")


# --- S13: rite's leftovers are not the project's content ---------------------


LEFTOVERS = {
    "hidden entries": lambda d: (d / ".claude").mkdir(),
    "rite's installer": lambda d: (d / "install.sh").write_text(RITE_INSTALLER),
    "a generated CLAUDE.md": lambda d: (d / "CLAUDE.md").write_text(
        GENERATED_CLAUDE_MD
    ),
    "rite Worker workspaces": lambda d: (
        (d / "workers" / "w1").mkdir(parents=True),
        (d / "workers" / "w1" / "worker.yml").write_text("worker: {}\n"),
    ),
}
CONTENT = {
    "someone else's install.sh": lambda d: (d / "install.sh").write_text(
        "#!/bin/sh\nmake install\n"
    ),
    "a CLAUDE.md a person wrote": lambda d: (d / "CLAUDE.md").write_text(
        "# our rules\n"
    ),
    "a README": lambda d: (d / "README.md").write_text("x\n"),
    "a workers/ with something else in it": lambda d: (
        (d / "workers").mkdir(exist_ok=True),
        (d / "workers" / "notes.txt").write_text("x\n"),
    ),
}


@pytest.mark.parametrize(
    "leftovers,content",
    [
        (subset, extra)
        for n in range(len(LEFTOVERS) + 1)
        for subset in itertools.combinations(LEFTOVERS, n)
        for extra in [None, *CONTENT]
    ],
)
def test_holds_nothing_is_exactly_no_content_besides_rites_own(
    tmp_path, leftovers, content
):
    """Every combination of rite's leftovers, alone and with each kind of
    real content: the directory holds nothing exactly when there is no real
    content, whatever rite left beside it."""
    d = tmp_path / "d"
    d.mkdir()
    for name in leftovers:
        LEFTOVERS[name](d)
    if content is not None:
        CONTENT[content](d)
    assert holds_nothing(d) == (content is None)
    assert bool(content_entries(d)) == (content is not None)


@pytest.mark.parametrize("leftover", list(LEFTOVERS))
def test_rites_leftovers_alone_are_not_code_in_no_repository(tmp_path, leftover):
    """S12's "code but no repository" is said of real code only: a directory
    holding only what rite left there is told it has no module, not that its
    code needs a repository."""
    from rite_ai.cli.init.detect import holds_files_but_no_repository

    d = tmp_path / "d"
    d.mkdir()
    LEFTOVERS[leftover](d)
    assert not holds_files_but_no_repository(d)
    out = _init(d, "--yes")
    assert "has code in it but is not a git repository" not in out
    assert "No module would be registered" in out
    (d / "main.go").write_text("package main\n")
    assert holds_files_but_no_repository(d)


# --- S21: the schedule is a stated default ------------------------------------


def _now(schedule):
    from rite_ai.schedule import current_moment

    moment = current_moment(schedule.timezone, datetime.now().astimezone())
    return moment.minute_of_day, moment.weekday


def test_a_fresh_project_gets_one_worker_all_day_in_the_machines_zone(tmp_path):
    root = _repo(tmp_path / "app")
    out = _init(root, "--yes")
    s = _config(root).schedule
    assert [(w.hours, w.workers, w.days) for w in s.windows] == [("00:00-24:00", 1, "")]
    zone = machine_zone_name()
    assert s.timezone in (zone, "")
    assert workers_at(s, *_now(s)) == 1
    assert "Schedule (default): 1 Worker(s) at a time, all day, every day" in out
    assert "rite schedule set" in out


def test_the_config_sets_it_and_says_so(tmp_path):
    root = _repo(tmp_path / "app")
    preset = tmp_path / "p.yaml"
    preset.write_text(
        "schedule:\n  timezone: UTC\n  workers: 3\n  hours: '09:00-17:00'\n"
    )
    out = _init(root, "--yes", "--config", str(preset))
    s = _config(root).schedule
    assert s.timezone == "UTC"
    assert [(w.hours, w.workers) for w in s.windows] == [("09:00-17:00", 3)]
    assert "Schedule (--config): 3 Worker(s) at a time, 09:00-17:00" in out


def test_an_existing_projects_schedule_is_untouched(tmp_path):
    root = _repo(tmp_path / "app")
    _init(root, "--yes")
    cfg = root / ".rite" / "config.yaml"
    raw = yaml.safe_load(cfg.read_text())
    raw["schedule"] = {
        "timezone": "UTC",
        "windows": [{"hours": "10:00-12:00", "workers": 2}],
    }
    cfg.write_text(yaml.safe_dump(raw))
    # Re-running init on an existing project records a change and nothing else.
    _init(root, input="y\n\nplease rename it\n\n")
    s = _config(root).schedule
    assert [(w.hours, w.workers) for w in s.windows] == [("10:00-12:00", 2)]


@pytest.mark.parametrize(
    "args,answers",
    [
        (["--yes"], None),
        ([], "n\n" + "\n" * 10 + "3\n" + "\n" * 20 + "n\n"),
        ([], "y\n\n\n\n\n\nn\n"),
    ],
    ids=["yes", "scratch", "existing-code"],
)
@pytest.mark.parametrize("with_code", [False, True])
def test_no_route_leaves_the_schedule_empty_or_unsaid(
    tmp_path, args, answers, with_code
):
    root = _repo(tmp_path / "app") if with_code else tmp_path / "app"
    root.mkdir(exist_ok=True)
    out = _init(root, *args, input=answers)
    s = _config(root).schedule
    assert s.windows and workers_at(s, *_now(s)) >= 1
    assert "Schedule (" in out


# --- S20: a Worker is offered ---------------------------------------------------


def test_accepting_the_offer_declares_a_worker_with_the_module(tmp_path):
    root = _repo(tmp_path / "app")
    # existing code? y · path · changes · role · add ./? · Worker? Enter · name
    out = _init(root, input="y\n\n\n\n\n\n\n\n")
    assert (root / "workers" / "w1" / "worker.yml").is_file()
    assert (root / "workers" / "w1" / "app" / "main.go").is_file()
    assert "Ready. Start a Dispatch session" in out


def test_declining_says_a_worker_is_needed(tmp_path):
    root = _repo(tmp_path / "app")
    out = _init(root, input="y\n\n\n\n\n\nn\n")
    assert not (root / "workers").exists()
    assert "NOT ready for work: no Worker is declared" in out
    assert "rite add worker w1" in out


def test_yes_declares_none_and_says_so(tmp_path):
    root = _repo(tmp_path / "app")
    out = _init(root, "--yes")
    assert not (root / "workers").exists()
    assert "no Worker is declared" in out and "Ready. Start" not in out


def test_the_config_can_declare_one(tmp_path):
    root = _repo(tmp_path / "app")
    preset = tmp_path / "p.yaml"
    preset.write_text("workers:\n  add: bob\n")
    out = _init(root, "--yes", "--config", str(preset))
    assert (root / "workers" / "bob" / "app" / "main.go").is_file()
    assert "Ready. Start a Dispatch session" in out


def test_no_module_means_no_offer(tmp_path):
    root = tmp_path / "empty"
    root.mkdir()
    out = _init(root, input="y\n\n\n\n\n")
    assert "Declare a Worker now" not in out


# --- S18: the credential namespace ---------------------------------------------


@pytest.mark.parametrize(
    "a,b",
    [
        ("https://github.com/Owner/Repo.git", "git@github.com:owner/repo"),
        ("ssh://git@github.com/owner/repo/", "https://github.com/owner/repo"),
        ("https://user@github.com/owner/repo.git", "github.com:owner/repo.git"),
    ],
)
def test_one_repository_is_one_remote_however_it_is_spelled(a, b):
    assert store.normalise_remote(a) == store.normalise_remote(b) != ""


def test_different_repositories_stay_different():
    assert store.normalise_remote(
        "https://github.com/owner/repo"
    ) != store.normalise_remote("https://github.com/owner/repo2")
    assert store.normalise_remote(
        "https://github.com/owner/repo"
    ) != store.normalise_remote("https://gitlab.com/owner/repo")


def _hold(namespace: str, key: str = "jira_token") -> None:
    """What `rite credential set` leaves in the registry: the account name."""
    path = store.default_rite_home() / "credentials.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    data = json.loads(path.read_text()) if path.is_file() else {}
    data[f"{namespace}/{key}"] = time.time()
    path.write_text(json.dumps(data))


URL = "https://github.com/robbartoszewski/yoloai.git"
SPELLINGS = {
    "the same URL": URL,
    "the ssh spelling": "git@github.com:robbartoszewski/yoloai",
    "another repository": "https://github.com/robbartoszewski/other.git",
}


@pytest.mark.parametrize(
    "recorded,held,answer",
    list(itertools.product(SPELLINGS, [True, False], ["y", "n", "--yes"])),
)
def test_a_reinit_offers_the_namespace_exactly_when_it_is_this_repos_and_held(
    tmp_path, recorded, held, answer
):
    """The invariant: offered iff the recorded remote is this module's (in any
    spelling) AND credentials are stored under it; reused iff offered and
    taken (`--yes` takes the default, yes). Otherwise a fresh namespace."""
    old = "yoloai-0ld0ld00"
    store.remember_namespace(old, [SPELLINGS[recorded]], "yoloai")
    if held:
        _hold(old)
    root = _repo(tmp_path / "yoloai", origin=URL)
    offered = recorded != "another repository" and held
    if answer == "--yes":
        out = _init(root, "--yes")
    else:
        # existing code? y · path · changes · role · add ./? · [reuse?] · Worker? n
        out = _init(
            root, input="y\n\n\n\n\n\n" + (f"{answer}\n" if offered else "") + "n\n"
        )
    assert (f"namespace {old}" in out) == offered
    reused = _config(root).credentials.namespace == old
    assert reused == (offered and answer != "n")
    if not reused:
        assert _config(root).credentials.namespace.startswith("yoloai-")


def test_a_wiped_reinit_offers_back_the_namespace_it_wiped(tmp_path):
    """A project made before the record existed: the wipe records it first."""
    root = _repo(tmp_path / "yoloai", origin=URL)
    _init(root, "--yes")
    old = _config(root).credentials.namespace
    (store.default_rite_home() / store.NAMESPACES_FILENAME).unlink()
    _hold(old)
    # existing code? n · wipe? y · … from scratch, every default · Manager?
    # Enter (S15) · reuse? y · Worker? n
    out = _init(
        root,
        input="n\ny\n" + "\n" * 10 + "3\n" + "\n" * 4 + "\ny\nn\n",
    )
    assert f"namespace {old}" in out
    assert _config(root).credentials.namespace == old


def test_rm_rf_and_a_fresh_clone_get_their_credentials_back(tmp_path):
    root = _repo(tmp_path / "yoloai", origin=URL)
    _init(root, "--yes")
    old = _config(root).credentials.namespace
    _hold(old, "github_token")
    shutil.rmtree(root)
    root = _repo(tmp_path / "yoloai", origin=URL)
    out = _init(root, "--yes")
    assert f"--yes: reused namespace {old}" in out
    assert "github_token" in out
    assert _config(root).credentials.namespace == old


def test_a_new_project_gets_a_fresh_namespace_and_no_offer(tmp_path):
    root = _repo(tmp_path / "fresh", origin="https://github.com/o/fresh.git")
    out = _init(root, "--yes")
    assert "Reusing it keeps them" not in out
    assert _config(root).credentials.namespace.startswith("fresh-")


def test_setting_a_credential_records_the_namespace_for_the_repository(
    tmp_path, monkeypatch
):
    """A project initialised before the record existed is noted the first time
    a credential is stored, so a later reset still gets it back."""
    from rite_ai.cli import main as cli_main

    root = _repo(tmp_path / "yoloai", origin=URL)
    _init(root, "--yes")
    (store.default_rite_home() / store.NAMESPACES_FILENAME).unlink()
    monkeypatch.setattr(store, "store", lambda account, value: store.STORED)
    config = _config(root)
    cli_main._store_one("jira_token", "x", False, root, config)
    _hold(config.credentials.namespace)
    (m,) = store.namespaces_for([URL])
    assert m.namespace == config.credentials.namespace
    assert m.keys == ("jira_token",)
