"""A Manager improvised `claude -p` because nothing told it otherwise.

**Measured, on the first run that got far enough to try.** The Manager
assigned both tickets correctly, then launched its Workers itself — "each
running `claude -p --dangerously-skip-permissions` in its own workspace" —
and both died immediately:

    Failed to authenticate: OAuth session expired and could not be refreshed

That is not a Worker machinery defect. `rite sandbox start` delivers the
project's Claude credential through `--env` (D-31), and the credential was
set; running the engine by hand bypasses the whole path, so the Worker got
no credentials at all. The instruction never said which command to use, and
improvising from silence was a reasonable inference.

⚠ **The instruction text is generated by this release**, which makes this
release's defect a Manager that cannot start a Worker.
"""

from __future__ import annotations

from rite_ai.managers.prompt import for_manager


class TestItSaysWhatToRun:
    def test_the_command_is_named(self):
        """Not just a prohibition: a Manager told only what NOT to do has
        the same problem it started with."""
        assert "rite sandbox start" in for_manager("lead")

    def test_it_says_how_to_give_the_worker_its_work(self):
        """`rite sandbox start` cannot be typed into afterwards, so the
        ticket has to go in at launch or the Worker sits idle."""
        text = for_manager("lead")
        assert "--ticket" in text or "--prompt" in text

    def test_it_says_workers_must_exist_first(self):
        assert "rite add worker" in for_manager("lead")


class TestItIsHardToMisreadUnderPressure:
    def test_running_the_engine_directly_is_named_and_refused(self):
        """⚠ A Manager runs unattended with no permission gate. If the
        phrasing leaves room for "I'll just run the engine directly", it
        eventually will — so the wrong thing is named explicitly rather
        than left to be inferred from the right one."""
        text = for_manager("lead")
        assert "claude" in text
        assert "never" in text.lower() or "do not" in text.lower()

    def test_the_consequence_is_stated_not_implied(self):
        """ "Because I said so" loses to a plausible shortcut at 3am. The
        reason it fails has to be in the text."""
        text = for_manager("lead").lower()
        assert "credential" in text
        assert "die" in text or "fail" in text


class TestItNamesTheCommandThatAnswersTheQuestionAsked:
    """⚠ Found while checking the rest of the prompt for the same shape.

    The instruction said "`rite loop status` says what is ready and what is
    stuck". It does not — it reports whether a LOOP PROCESS is running
    ("loop: not running — no tmux session for this project"). A Manager
    sent there for the queue gets an answer about tmux, and the one that
    hit this concluded the command "doesn't exist in this version of rite"
    and spent its first turn on the confusion.

    Prose and code drifting in the direction that flatters the tool, in
    generated instruction text — `DEFECT_CLASSES.md` class 6, and the same
    class as the Worker defect this file is mostly about."""

    def test_the_queue_command_is_the_one_that_prints_the_queue(self):
        text = for_manager("lead")
        assert "rite loop run" in text

    def test_the_other_command_is_not_promised_to_answer_it(self):
        """`rite loop status` may still be mentioned — it must not be
        offered as the way to see what is ready."""
        text = for_manager("lead")
        if "rite loop status" in text:
            assert "different question" in text or "whether a loop" in text


class TestTheRestOfTheInstructionStillHolds:
    def test_the_manager_still_knows_who_it_is(self):
        assert "'planner'" in for_manager("planner")

    def test_extra_is_still_appended_verbatim(self):
        assert for_manager("lead", extra="\n\nEXTRA").endswith("EXTRA")
