"""SCRUM-68 — a release tag at HEAD must not turn CI red, and a skip is not
the fix.

§1's must-fix row: *"A release tag at HEAD turns CI red: the tag-relative
guards and every-test-passes-somewhere need a declared 'nothing to check'
state; lands before the re-cut."* Robert ruled it IN on 2026-10-05, sequenced
before the RC re-cut so the re-cut does not need the follow-up PR a9 did.

🔴 **The failure.** Two guards ask what the last release SHIPPED and compare
it against a table generated by `tools/template_history.py` /
`tools/section_history.py` — tools that read git TAGS and therefore run AFTER
the tag exists. At the moment the tag is created the table cannot carry it, so
the guard fails on a release that has done nothing wrong, on main, while
somebody is cutting a release.

🔴 **And `pytest.skip` is NOT the fix.** A test that skips in every job passes
NOWHERE, and `tools/every_test_passes_somewhere.py` turns that into a red
check — `.github/workflows/ci.yml` says so in its own comment: *"a check that
skips in CI reports the same green as one that passed."* Skipping moves the
redness. Hence a **declared** state: the guard passes, having said what it did
not check and why, and judges the newest tag that is NOT at HEAD so coverage
continues against a real release.
"""

from __future__ import annotations

import subprocess

import pytest
from _pytest.outcomes import Skipped as _Skipped

import released_tags

# --- 1. ordering is by VERSION, which is the silent half of this ticket ------


def test_a_release_sorts_after_its_own_pre_releases():
    """🔴 `sorted(["v0.7.0a9", "v0.7.0"])` ends in `v0.7.0a9`. A guard
    ordering strings would, the moment `v0.7.0` was cut, go on judging the
    last ALPHA and stop checking the release — silently, which is worse than
    the redness this ticket is about. `test_update_refresh`'s template half
    sorted strings until now; its section half already did not."""
    assert released_tags.by_version(["v0.7.0a9", "v0.7.0"]) == ["v0.7.0a9", "v0.7.0"]
    assert sorted(["v0.7.0a9", "v0.7.0"])[-1] == "v0.7.0a9", (
        "if this ever changes, the bug above stopped being possible"
    )


def test_two_digit_minors_sort_as_numbers():
    assert released_tags.by_version(["v0.10.0", "v0.4.0", "v0.9.0"]) == [
        "v0.4.0",
        "v0.9.0",
        "v0.10.0",
    ]


def test_a_tag_that_is_not_a_version_is_dropped_not_ordered_arbitrarily():
    """A tag that is not a version says nothing about which release is
    newest, so it must not be able to BECOME the newest."""
    got = released_tags.by_version(["v0.4.0", "nightly", "v0.5.0", "v-latest"])
    assert got == ["v0.4.0", "v0.5.0"]


# --- 2. `judge`, against real git repositories -------------------------------


def _repo(tmp_path, *, tags=(), tag_head=()):
    """A repository with two commits, `tags` on the first and `tag_head` on
    the second (HEAD)."""
    repo = tmp_path / "r"
    repo.mkdir()

    def git(*args):
        subprocess.run(["git", "-C", str(repo), *args], check=True, capture_output=True)

    git("init", "-q")
    git("config", "user.email", "t@example.com")
    git("config", "user.name", "T")
    (repo / "a").write_text("one\n")
    git("add", "a")
    git("commit", "-qm", "first")
    for tag in tags:
        git("tag", tag)
    (repo / "a").write_text("two\n")
    git("commit", "-aqm", "second")
    for tag in tag_head:
        git("tag", tag)
    return repo


def test_a_tagless_checkout_is_the_one_case_a_guard_may_SKIP(tmp_path):
    """A checkout shape, not a release state: there is no release to judge
    and nothing is being hidden."""
    got = released_tags.judge(_repo(tmp_path))
    assert got.tag is None and got.declared == ""
    assert "no release tags" in got.nothing


def test_the_newest_tag_is_judged_when_it_is_not_at_head(tmp_path):
    """The ordinary case, and the control for everything below."""
    got = released_tags.judge(_repo(tmp_path, tags=("v0.6.0", "v0.7.0")))
    assert got.tag == "v0.7.0"
    assert got.declared == "" and got.nothing == ""


def test_a_tag_AT_HEAD_is_declared_and_the_previous_release_is_judged(tmp_path):
    """🔴 The headline. Nothing fails, nothing skips, and the run says what it
    did not check — while coverage continues against a release that HAS been
    regenerated for."""
    got = released_tags.judge(_repo(tmp_path, tags=("v0.7.0a9",), tag_head=("v0.7.0",)))
    assert got.nothing == "", "this is not a reason to skip"
    assert got.tag == "v0.7.0a9", "the previous release is still judged"
    assert "v0.7.0 is AT HEAD" in got.declared
    assert "read git tags and run after the tag exists" in got.declared
    assert "SCRUM-68" in got.declared
    assert "next commit makes this guard live again" in got.declared


def test_only_tag_at_head_leaves_nothing_to_judge_but_still_does_not_skip(tmp_path):
    """The first release ever: the tag is at HEAD and there is no earlier one.
    Still not a skip — `nothing` stays empty and the guard reports."""
    got = released_tags.judge(_repo(tmp_path, tag_head=("v0.1.0",)))
    assert got.tag is None
    assert got.nothing == "", "a declared state is not a skip"
    assert "v0.1.0 is AT HEAD" in got.declared


def test_several_tags_at_head_are_all_declared(tmp_path):
    """A re-cut puts two tags on one commit. The newest of them is named and
    the newest EARLIER release is judged."""
    got = released_tags.judge(
        _repo(tmp_path, tags=("v0.6.0",), tag_head=("v0.7.0a9", "v0.7.0"))
    )
    assert got.tag == "v0.6.0"
    assert "v0.7.0 is AT HEAD" in got.declared


def test_it_asks_points_at_HEAD_and_not_describe():
    """⚠ `git describe` answers with the NEAREST tag whether or not it is at
    the commit, which is the opposite of the question. A guard built on it
    would declare "nothing to check" for every commit after a tag — that is,
    for ever."""
    import inspect

    src = inspect.getsource(released_tags.tags_at_head)
    assert '"tag", "--points-at", "HEAD"' in src
    assert "describe" not in src.split('"""')[2]


def test_this_checkout_agrees_with_itself(tmp_path):
    """Against the real repository, whatever state it is in: `judge` either
    names a tag this checkout has, or says why it cannot."""
    from pathlib import Path

    repo = Path(__file__).resolve().parent.parent
    got = released_tags.judge(repo)
    if got.nothing:
        assert got.tag is None
        return
    if got.tag is not None:
        assert got.tag in released_tags.release_tags(repo)
        assert got.tag not in released_tags.tags_at_head(repo)


# --- 3. the guards themselves do not skip on the declared state --------------


def _guard(method_name: str):
    """The guard, found the way pytest imports it — a BARE import.

    ⚠ `from tests import test_update_refresh` imports the same file under a
    second name, and a dataclass defined in it then resolves its annotations
    against a module that is not the one its class remembers. Measured here:
    it raised inside `dataclasses` rather than failing the assertion. `tests/`
    is on `pythonpath` (pyproject) precisely so the bare form works.
    """
    import inspect

    import test_update_refresh as module

    for _name, obj in inspect.getmembers(module, inspect.isclass):
        for name, value in inspect.getmembers(obj):
            if name == method_name and callable(value):
                return module, obj, name
    raise AssertionError(f"no class in test_update_refresh has {method_name}")


class _NoSkip:
    """A `pytest` stand-in whose `skip` is a failure. A guard reaching it on a
    DECLARED state is the defect this ticket is about."""

    @staticmethod
    def skip(reason=""):
        raise AssertionError(
            f"the guard SKIPPED on a declared state ({reason!r}); a test that "
            "skips in every job passes nowhere and turns "
            "every-test-passes-somewhere red"
        )


@pytest.mark.parametrize(
    "guard",
    [
        "test_the_history_covers_what_the_last_release_shipped",
        "test_the_history_covers_the_newest_release",
    ],
)
@pytest.mark.parametrize(
    "judgement",
    [
        released_tags.Judgement(tag=None, declared="v0.1.0 is AT HEAD …"),
    ],
    ids=["only-tag-at-head"],
)
def test_a_guard_PASSES_rather_than_skipping_on_a_declared_state(
    monkeypatch, guard, judgement
):
    """🔴 Behaviourally, and this is the property the whole ticket turns on: a
    test that skips in every job passes NOWHERE, and
    `every-test-passes-somewhere` turns that red. A declared state must
    therefore PASS."""
    module, cls, name = _guard(guard)
    monkeypatch.setattr(module.released_tags, "judge", lambda _root: judgement)
    monkeypatch.setattr(module, "pytest", _NoSkip())
    getattr(cls(), name)()


@pytest.mark.parametrize(
    "guard",
    [
        "test_the_history_covers_what_the_last_release_shipped",
        "test_the_history_covers_the_newest_release",
    ],
)
def test_a_guard_STILL_skips_a_tagless_checkout(monkeypatch, guard):
    """The control, and the boundary: a checkout shape genuinely has nothing
    to judge, and that one IS a skip — the behaviour before this ticket, kept."""
    module, cls, name = _guard(guard)
    monkeypatch.setattr(
        module.released_tags,
        "judge",
        lambda _root: released_tags.Judgement(nothing="no release tags here"),
    )
    # ⚠ `pytest.skip` raises `Skipped`, which derives from BaseException —
    # `pytest.raises(Exception)` does not catch it, and the test itself would
    # skip while appearing to assert something.
    with pytest.raises(BaseException) as raised:  # noqa: B017, PT011
        getattr(cls(), name)()
    assert isinstance(raised.value, _Skipped)
    assert "no release tags here" in str(raised.value)


@pytest.mark.parametrize(
    "guard",
    [
        "test_the_history_covers_what_the_last_release_shipped",
        "test_the_history_covers_the_newest_release",
    ],
)
def test_a_guard_still_FAILS_a_release_the_tables_do_not_carry(monkeypatch, guard):
    """The other control, and the one that matters most: the fix must not have
    turned the guard off. A real tag whose templates/sections are missing from
    the generated table still fails."""
    module, cls, name = _guard(guard)
    monkeypatch.setattr(
        module.released_tags,
        "judge",
        lambda _root: released_tags.Judgement(tag="v0.0.1-not-a-real-tag"),
    )
    with pytest.raises(Exception):
        getattr(cls(), name)()


# --- 4. the tool the ticket groups in has no vacuous pass --------------------


def test_every_test_passes_somewhere_refuses_an_empty_report(tmp_path):
    """⚠ Checked rather than assumed. The reason a declared state is needed at
    all is that this tool is strict: a report with no test cases is
    `CannotTell`, not a pass. If it ever became lenient, skipping would stop
    being red and this whole fix would look unnecessary while the hole it
    covers reopened."""
    import importlib.util
    import sys
    from pathlib import Path

    tool_path = (
        Path(__file__).resolve().parent.parent
        / "tools"
        / "every_test_passes_somewhere.py"
    )
    spec = importlib.util.spec_from_file_location(
        "every_test_passes_somewhere", tool_path
    )
    tool = importlib.util.module_from_spec(spec)
    # ⚠ Registered BEFORE exec. The tool defines a dataclass, and
    # `dataclasses` resolves its annotations through
    # `sys.modules[cls.__module__]` — which is None for a module loaded by
    # path and never registered, so the import itself raised inside
    # `dataclasses` rather than anything failing here.
    sys.modules[spec.name] = tool
    spec.loader.exec_module(tool)

    empty = tmp_path / "empty.xml"
    empty.write_text('<?xml version="1.0"?><testsuites></testsuites>')
    with pytest.raises(tool.CannotTell) as raised:
        tool.read_report(empty)
    assert "holds no test cases" in str(raised.value)


# --- 5. the sibling guard SCRUM-68 did not reach -----------------------------


def test_the_release_checksum_guards_stand_down_as_a_PASS_not_a_skip():
    """🔴 **Measured on the 0.7.0a10 bump, after SCRUM-68 landed.** Two tests
    in `test_release_checksums` need `VERSION`'s tag to exist, and it cannot
    during the bump-then-tag window — the tag goes on the commit that carries
    the bumped VERSION, so between "bump merged" and "tag pushed" there is no
    tag, and that window is a CI run.

    They were `pytest.mark.skipif`, so they skipped in EVERY job of the matrix,
    passed NOWHERE, and `every-test-passes-somewhere` turned the whole run red
    with all four suites at 0 failed. The same failure SCRUM-68 fixed for the
    history guards, on a guard it did not reach.

    So: a stand-down that PASSES, having said what it did not check.
    """
    import ast
    import pathlib as _pathlib

    import test_release_checksums as module

    # ⚠ By AST. The comment in that file RECORDS that it used to be a
    # `pytest.mark.skipif`, so a source-text check trips on its own prose —
    # which is the mistake two of this batch's earlier guards made.
    tree = ast.parse(_pathlib.Path(module.__file__).read_text())
    for node in ast.walk(tree):
        if not isinstance(node, ast.Attribute) or node.attr != "skipif":
            continue
        raise AssertionError(
            f"{module.__file__}:{node.lineno} uses skipif: it skips in every "
            "job, so the test passes nowhere and every-test-passes-somewhere "
            "turns the run red"
        )
    assert hasattr(module, "NOTHING_TO_CHECK_YET")
    # The stand-down says what it did not check, and why it will run later.
    assert "NOTHING for this to check" in module.NOTHING_TO_CHECK_YET
    assert "runs for real the moment the tag is created" in module.NOTHING_TO_CHECK_YET


def test_the_stand_down_still_RUNS_the_body_once_the_tag_exists(monkeypatch):
    """The control, and the one that matters: this must not become a test that
    never runs. With the tag present the body executes; without it, it does
    not — and either way the test passes."""
    import test_release_checksums as module

    ran: list[str] = []

    @module.needs_release_tag
    def guarded(tmp_path=None):
        ran.append("body")

    monkeypatch.setattr(module, "_RELEASE_TAG_EXISTS", False)
    guarded()
    assert ran == [], "the body must not run without the tag"

    monkeypatch.setattr(module, "_RELEASE_TAG_EXISTS", True)
    guarded()
    assert ran == ["body"], "the body MUST run once the tag exists"


def test_the_stand_down_keeps_the_fixtures_the_test_asked_for():
    """⚠ `functools.wraps` keeps `__wrapped__`, which is how pytest still sees
    a wrapped test's fixtures. Without it `tmp_path` would not be supplied and
    the test would fail for an unrelated reason — passing a guard while
    breaking the thing it guards."""
    import inspect

    import test_release_checksums as module

    for name in (
        "test_it_hashes_the_tag_not_head_once_the_tag_exists",
        "test_it_refuses_to_publish_a_digest_of_an_uncommitted_working_copy",
    ):
        fn = getattr(module, name)
        assert hasattr(fn, "__wrapped__"), name
        assert "tmp_path" in inspect.signature(fn).parameters, name
