"""A local unit also gets `AGENTS.md`, from the same body (SCRUM-49).

🔴 Goose does not read `CLAUDE.md` — measured in
`docs/design/spikes/SCRUM-48-one-agents-md-for-both-engines.md`, where a rule in
`AGENTS.md` was honoured and the same rule in `CLAUDE.md` was not, and where
`CLAUDE.md` appears zero times in the Goose binary. rite wrote only `CLAUDE.md`,
so every local Manager and local Worker received no standing instructions at all.

⚠ **The DRY property is tested, not just the existence of the file.** Robert's
instruction was that `AGENTS.md`'s body come from where `CLAUDE.md`'s already
comes from, so SCRUM-48 flips one source. Two files generated by two code paths
would satisfy "the file exists" and still drift, so the assertions below compare
the two files' CONTENT rather than checking each against a fixture.
"""

from __future__ import annotations

from pathlib import Path

from rite_ai.config.models import (
    CoordinationConfig,
    ProjectConfig,
    WorkerManifest,
)
from rite_ai.instruction_files import instruction_files, project_runs_a_local_engine

GPU = {
    "endpoint": "http://localhost:11434",
    "agent": "goose",
    "context_window": 32768,
}


def _local_worker(name: str = "w1") -> WorkerManifest:
    return WorkerManifest(
        name=name,
        manager="lead",
        modules=["svc"],
        engine="local:small",
        model="qwen3:8b",
        **GPU,
    )


# ── the policy, in one place ──────────────────────────────────────────────────


def test_a_claude_unit_gets_only_claude_md(tmp_path):
    assert instruction_files(tmp_path, local=False) == (tmp_path / "CLAUDE.md",)


def test_a_local_unit_gets_both(tmp_path):
    assert instruction_files(tmp_path, local=True) == (
        tmp_path / "CLAUDE.md",
        tmp_path / "AGENTS.md",
    )


def test_claude_md_comes_first_so_it_is_never_the_one_that_is_missing(tmp_path):
    # Order matters only in that CLAUDE.md is not conditional: a writer that
    # stops early must still have written the file every reader expects.
    assert instruction_files(tmp_path, local=True)[0].name == "CLAUDE.md"


def test_a_project_with_a_local_manager_runs_a_local_engine():
    from rite_ai.config.managers import ManagerRole

    config = ProjectConfig(
        coordination=CoordinationConfig(
            manager_roles=[
                ManagerRole(name="lead", engine="claude"),
                ManagerRole(name="gpu", engine="local:small", model="qwen3:8b", **GPU),
            ]
        )
    )
    assert project_runs_a_local_engine(config) is True


def test_an_all_claude_project_does_not():
    from rite_ai.config.managers import ManagerRole

    config = ProjectConfig(
        coordination=CoordinationConfig(
            manager_roles=[ManagerRole(name="lead", engine="claude")]
        )
    )
    assert project_runs_a_local_engine(config) is False


def test_a_project_with_no_managers_does_not():
    assert project_runs_a_local_engine(ProjectConfig()) is False


def test_something_it_cannot_read_is_not_guessed_as_local():
    # Guessing True would write a file no engine reads.
    assert project_runs_a_local_engine(object()) is False
    assert project_runs_a_local_engine(None) is False


# ── the Worker writer ─────────────────────────────────────────────────────────


def _write_worker(tmp_path: Path, manifest: WorkerManifest) -> Path:
    from rite_ai.workspace.manage import _write_worker_claude_config

    worker_dir = tmp_path / "workers" / manifest.name
    worker_dir.mkdir(parents=True)
    _write_worker_claude_config(worker_dir, manifest)
    return worker_dir


def test_a_local_workers_sandbox_has_agents_md_with_the_generated_body(tmp_path):
    worker_dir = _write_worker(tmp_path, _local_worker())
    agents = worker_dir / "AGENTS.md"
    assert agents.is_file(), "a local Worker got no AGENTS.md"
    body = agents.read_text()
    # It is the generated body, not a stub pointing elsewhere.
    assert "## " in body
    assert "lead" in body


def test_the_two_files_hold_the_same_body(tmp_path):
    """⚠ The DRY property. Two files from two code paths would pass a
    file-exists test and still drift."""
    worker_dir = _write_worker(tmp_path, _local_worker())
    assert (worker_dir / "AGENTS.md").read_text() == (
        worker_dir / "CLAUDE.md"
    ).read_text()


def test_the_body_is_the_one_the_renderer_produces(tmp_path):
    # Pinned against the single source, so a second generator cannot satisfy it.
    from rite_ai.workspace.manage import render_worker_claude_md

    manifest = _local_worker()
    worker_dir = _write_worker(tmp_path, manifest)
    assert (worker_dir / "AGENTS.md").read_text() == render_worker_claude_md(manifest)


def test_a_claude_worker_gets_no_agents_md(tmp_path):
    worker_dir = _write_worker(tmp_path, WorkerManifest(name="w2", manager="lead"))
    assert (worker_dir / "CLAUDE.md").is_file()
    assert not (worker_dir / "AGENTS.md").exists(), (
        "a Claude Worker gained a file nothing reads"
    )


def test_a_local_worker_still_gets_everything_it_got_before(tmp_path):
    # The change is additive: CLAUDE.md and the review convention are untouched.
    worker_dir = _write_worker(tmp_path, _local_worker())
    assert (worker_dir / "CLAUDE.md").is_file()
    assert (worker_dir / ".claude").is_dir()


# ── the project root (`rite init`) ────────────────────────────────────────────


def _brief():
    from rite_ai.config.models import ProjectBrief

    return ProjectBrief(name="acme", role="owner")


def _config_with(engine: str) -> ProjectConfig:
    from rite_ai.config.managers import ManagerRole

    extra = GPU if engine.startswith("local:") else {}
    model = "qwen3:8b" if engine.startswith("local:") else ""
    return ProjectConfig(
        coordination=CoordinationConfig(
            manager_roles=[
                ManagerRole(name="lead", engine=engine, model=model, **extra)
            ]
        )
    )


def test_a_project_with_a_local_manager_gets_a_root_agents_md(tmp_path):
    from rite_ai.cli.init.claude_gen import install_claude_config

    install_claude_config(tmp_path, "owner", _brief(), [], _config_with("local:small"))
    assert (tmp_path / "AGENTS.md").is_file()
    assert (tmp_path / "AGENTS.md").read_text() == (tmp_path / "CLAUDE.md").read_text()


def test_an_all_claude_project_gets_no_root_agents_md(tmp_path):
    from rite_ai.cli.init.claude_gen import install_claude_config

    install_claude_config(tmp_path, "owner", _brief(), [], _config_with("claude"))
    assert (tmp_path / "CLAUDE.md").is_file()
    assert not (tmp_path / "AGENTS.md").exists()


# ── `rite update` installs it into a project that predates the change ─────────


def test_update_delivers_agents_md_to_an_existing_local_project(tmp_path):
    """The migration path for a project created before SCRUM-49: it has a
    CLAUDE.md and no AGENTS.md, and `rite update` treats the absence as a gap."""
    from rite_ai.cli.init.claude_gen import install_claude_config

    config = _config_with("local:small")
    install_claude_config(tmp_path, "owner", _brief(), [], config)
    (tmp_path / "AGENTS.md").unlink()  # as a pre-SCRUM-49 project looks
    assert not (tmp_path / "AGENTS.md").exists()

    from rite_ai.cli.init.claude_gen import GENERATED_MARKER
    from rite_ai.update.refresh import _refresh_claude_md

    body = (tmp_path / "CLAUDE.md").read_text()
    result = _refresh_claude_md(
        tmp_path, tmp_path / "AGENTS.md", body, GENERATED_MARKER, frozenset(), True
    )
    assert (tmp_path / "AGENTS.md").is_file()
    assert [c.action for c in result.changes] == ["installed"]
