"""Every command line `launch_command` builds today, pinned byte for byte.

⚠ **THE TEST CU2's ACCEPTANCE CITED DID NOT EXIST.** The v0.6.0 plan
recorded Claude as "byte-identical across 54 argv combinations" (B3a), and the
v0.7.0 plan made that the bar for adding Cursor. No test in the tree
enumerated `launch_command`'s inputs: the byte-identity claim rested on three
spot checks in `test_manager_supervise_bounds.py`. So this is written FIRST,
against the code as it stood before Cursor, and a third engine is checked
against a pin rather than against a memory of one.

**The table is literal on purpose.** It was generated once from `origin/main`
at `1a8bf9d`, and it is not regenerated by the test: a table computed by the
code under test agrees with any change to that code. A change that alters a
row has to change the row here, in the same diff, where review sees it.

The axes are every input `launch_command` takes: four engines (the default,
`claude`, a Goose-backed `local:` tier, and a substituted stub binary), with
and without a resume id, a start handle, a prompt file (including a path that
needs quoting), and an argv permission. 4 × 2 × 2 × 3 × 2 = 96.
"""

from __future__ import annotations

import itertools

from rite_ai.managers.supervise import launch_command

ENGINES = [("", ""), ("claude", ""), ("local:large", "goose"), ("sh", "")]
RESUME = ["", "r1"]
START = ["", "h1"]
PROMPT = ["", "/p", "/a b/p"]
PERMISSION = ["", "--perm"]

PINNED = {
    ("", "", "", "", "", ""): "claude -p",
    ("", "", "", "", "", "--perm"): "claude -p --perm",
    ("", "", "", "", "/p", ""): "claude -p < /p",
    ("", "", "", "", "/p", "--perm"): "claude -p --perm < /p",
    ("", "", "", "", "/a b/p", ""): "claude -p < '/a b/p'",
    ("", "", "", "", "/a b/p", "--perm"): "claude -p --perm < '/a b/p'",
    ("", "", "", "h1", "", ""): "claude -p",
    ("", "", "", "h1", "", "--perm"): "claude -p --perm",
    ("", "", "", "h1", "/p", ""): "claude -p < /p",
    ("", "", "", "h1", "/p", "--perm"): "claude -p --perm < /p",
    ("", "", "", "h1", "/a b/p", ""): "claude -p < '/a b/p'",
    ("", "", "", "h1", "/a b/p", "--perm"): "claude -p --perm < '/a b/p'",
    ("", "", "r1", "", "", ""): "claude -p --resume r1",
    ("", "", "r1", "", "", "--perm"): "claude -p --perm --resume r1",
    ("", "", "r1", "", "/p", ""): "claude -p --resume r1 < /p",
    ("", "", "r1", "", "/p", "--perm"): "claude -p --perm --resume r1 < /p",
    ("", "", "r1", "", "/a b/p", ""): "claude -p --resume r1 < '/a b/p'",
    ("", "", "r1", "", "/a b/p", "--perm"): "claude -p --perm --resume r1 < '/a b/p'",
    ("", "", "r1", "h1", "", ""): "claude -p --resume r1",
    ("", "", "r1", "h1", "", "--perm"): "claude -p --perm --resume r1",
    ("", "", "r1", "h1", "/p", ""): "claude -p --resume r1 < /p",
    ("", "", "r1", "h1", "/p", "--perm"): "claude -p --perm --resume r1 < /p",
    ("", "", "r1", "h1", "/a b/p", ""): "claude -p --resume r1 < '/a b/p'",
    ("", "", "r1", "h1", "/a b/p", "--perm"): "claude -p --perm --resume r1 < '/a b/p'",
    ("claude", "", "", "", "", ""): "claude -p",
    ("claude", "", "", "", "", "--perm"): "claude -p --perm",
    ("claude", "", "", "", "/p", ""): "claude -p < /p",
    ("claude", "", "", "", "/p", "--perm"): "claude -p --perm < /p",
    ("claude", "", "", "", "/a b/p", ""): "claude -p < '/a b/p'",
    ("claude", "", "", "", "/a b/p", "--perm"): "claude -p --perm < '/a b/p'",
    ("claude", "", "", "h1", "", ""): "claude -p",
    ("claude", "", "", "h1", "", "--perm"): "claude -p --perm",
    ("claude", "", "", "h1", "/p", ""): "claude -p < /p",
    ("claude", "", "", "h1", "/p", "--perm"): "claude -p --perm < /p",
    ("claude", "", "", "h1", "/a b/p", ""): "claude -p < '/a b/p'",
    ("claude", "", "", "h1", "/a b/p", "--perm"): "claude -p --perm < '/a b/p'",
    ("claude", "", "r1", "", "", ""): "claude -p --resume r1",
    ("claude", "", "r1", "", "", "--perm"): "claude -p --perm --resume r1",
    ("claude", "", "r1", "", "/p", ""): "claude -p --resume r1 < /p",
    ("claude", "", "r1", "", "/p", "--perm"): "claude -p --perm --resume r1 < /p",
    ("claude", "", "r1", "", "/a b/p", ""): "claude -p --resume r1 < '/a b/p'",
    (
        "claude",
        "",
        "r1",
        "",
        "/a b/p",
        "--perm",
    ): "claude -p --perm --resume r1 < '/a b/p'",
    ("claude", "", "r1", "h1", "", ""): "claude -p --resume r1",
    ("claude", "", "r1", "h1", "", "--perm"): "claude -p --perm --resume r1",
    ("claude", "", "r1", "h1", "/p", ""): "claude -p --resume r1 < /p",
    ("claude", "", "r1", "h1", "/p", "--perm"): "claude -p --perm --resume r1 < /p",
    ("claude", "", "r1", "h1", "/a b/p", ""): "claude -p --resume r1 < '/a b/p'",
    (
        "claude",
        "",
        "r1",
        "h1",
        "/a b/p",
        "--perm",
    ): "claude -p --perm --resume r1 < '/a b/p'",
    ("local:large", "goose", "", "", "", ""): "goose run",
    ("local:large", "goose", "", "", "", "--perm"): "goose run",
    ("local:large", "goose", "", "", "/p", ""): "goose run -i /p",
    ("local:large", "goose", "", "", "/p", "--perm"): "goose run -i /p",
    ("local:large", "goose", "", "", "/a b/p", ""): "goose run -i '/a b/p'",
    ("local:large", "goose", "", "", "/a b/p", "--perm"): "goose run -i '/a b/p'",
    ("local:large", "goose", "", "h1", "", ""): "goose run -n h1",
    ("local:large", "goose", "", "h1", "", "--perm"): "goose run -n h1",
    ("local:large", "goose", "", "h1", "/p", ""): "goose run -n h1 -i /p",
    ("local:large", "goose", "", "h1", "/p", "--perm"): "goose run -n h1 -i /p",
    ("local:large", "goose", "", "h1", "/a b/p", ""): "goose run -n h1 -i '/a b/p'",
    (
        "local:large",
        "goose",
        "",
        "h1",
        "/a b/p",
        "--perm",
    ): "goose run -n h1 -i '/a b/p'",
    ("local:large", "goose", "r1", "", "", ""): "goose run -n r1 -r",
    ("local:large", "goose", "r1", "", "", "--perm"): "goose run -n r1 -r",
    ("local:large", "goose", "r1", "", "/p", ""): "goose run -n r1 -r -i /p",
    ("local:large", "goose", "r1", "", "/p", "--perm"): "goose run -n r1 -r -i /p",
    ("local:large", "goose", "r1", "", "/a b/p", ""): "goose run -n r1 -r -i '/a b/p'",
    (
        "local:large",
        "goose",
        "r1",
        "",
        "/a b/p",
        "--perm",
    ): "goose run -n r1 -r -i '/a b/p'",
    ("local:large", "goose", "r1", "h1", "", ""): "goose run -n r1 -r",
    ("local:large", "goose", "r1", "h1", "", "--perm"): "goose run -n r1 -r",
    ("local:large", "goose", "r1", "h1", "/p", ""): "goose run -n r1 -r -i /p",
    ("local:large", "goose", "r1", "h1", "/p", "--perm"): "goose run -n r1 -r -i /p",
    (
        "local:large",
        "goose",
        "r1",
        "h1",
        "/a b/p",
        "",
    ): "goose run -n r1 -r -i '/a b/p'",
    (
        "local:large",
        "goose",
        "r1",
        "h1",
        "/a b/p",
        "--perm",
    ): "goose run -n r1 -r -i '/a b/p'",
    ("sh", "", "", "", "", ""): "sh -p",
    ("sh", "", "", "", "", "--perm"): "sh -p --perm",
    ("sh", "", "", "", "/p", ""): "sh -p < /p",
    ("sh", "", "", "", "/p", "--perm"): "sh -p --perm < /p",
    ("sh", "", "", "", "/a b/p", ""): "sh -p < '/a b/p'",
    ("sh", "", "", "", "/a b/p", "--perm"): "sh -p --perm < '/a b/p'",
    ("sh", "", "", "h1", "", ""): "sh -p",
    ("sh", "", "", "h1", "", "--perm"): "sh -p --perm",
    ("sh", "", "", "h1", "/p", ""): "sh -p < /p",
    ("sh", "", "", "h1", "/p", "--perm"): "sh -p --perm < /p",
    ("sh", "", "", "h1", "/a b/p", ""): "sh -p < '/a b/p'",
    ("sh", "", "", "h1", "/a b/p", "--perm"): "sh -p --perm < '/a b/p'",
    ("sh", "", "r1", "", "", ""): "sh -p --resume r1",
    ("sh", "", "r1", "", "", "--perm"): "sh -p --perm --resume r1",
    ("sh", "", "r1", "", "/p", ""): "sh -p --resume r1 < /p",
    ("sh", "", "r1", "", "/p", "--perm"): "sh -p --perm --resume r1 < /p",
    ("sh", "", "r1", "", "/a b/p", ""): "sh -p --resume r1 < '/a b/p'",
    ("sh", "", "r1", "", "/a b/p", "--perm"): "sh -p --perm --resume r1 < '/a b/p'",
    ("sh", "", "r1", "h1", "", ""): "sh -p --resume r1",
    ("sh", "", "r1", "h1", "", "--perm"): "sh -p --perm --resume r1",
    ("sh", "", "r1", "h1", "/p", ""): "sh -p --resume r1 < /p",
    ("sh", "", "r1", "h1", "/p", "--perm"): "sh -p --perm --resume r1 < /p",
    ("sh", "", "r1", "h1", "/a b/p", ""): "sh -p --resume r1 < '/a b/p'",
    ("sh", "", "r1", "h1", "/a b/p", "--perm"): "sh -p --perm --resume r1 < '/a b/p'",
}


def _combinations():
    for (engine, agent), resume, start, prompt, permission in itertools.product(
        ENGINES, RESUME, START, PROMPT, PERMISSION
    ):
        yield (engine, agent, resume, start, prompt, permission)


def test_the_table_covers_every_combination_and_nothing_else():
    """A pin that silently lost rows would pass everything below."""
    combinations = list(_combinations())
    assert len(combinations) == 96
    assert set(combinations) == set(PINNED)


def test_every_command_line_is_unchanged():
    changed = {}
    for key in _combinations():
        engine, agent, resume, start, prompt, permission = key
        built = launch_command(
            engine, resume, prompt, permission, agent=agent, start_handle=start
        )
        if built != PINNED[key]:
            changed[key] = (PINNED[key], built)
    assert not changed, changed
