"""The project spec beyond pointing at one (SPEC §9.13.1, D-53).

D-52 made rite point Workers at a spec that already exists. A greenfield
project has none, and nothing produced one: the orientation table's "no
project spec" row had no code behind it, the generated `CLAUDE.md` told a
session to consult a table it did not contain, and a `SPEC.md` a session
did write reached no Worker until someone ran `rite spec add` — and never
reached the Owner, because only `rite init` wrote the Owner's `CLAUDE.md`.

This module is the rite side of `/spec`: the notices `rite start` and
`rite doctor` both print about the spec (one wording, so the two cannot
drift apart), and the refresh that rewrites the spec section of every
generated `CLAUDE.md` when the registered paths change.

**Not verified end to end:** no live Claude session has been run through
`/spec`, so whether one writes a usable spec from it is untested — that
costs quota and is not deterministic. What is tested is everything around
it: the command is installed and routed to, a file it writes is reported
if left unregistered, and registering it reaches every generated
`CLAUDE.md`.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from rite_ai.config.models import ProjectConfig
from rite_ai.generated_sections import back_over_marker
from rite_ai.state import write_atomic

# The spec section is the one part of a generated `CLAUDE.md` rewritten
# after it is first written. The markers are how it is found again.
SPEC_SECTION_START = "<!-- rite:spec -->"
SPEC_SECTION_END = "<!-- /rite:spec -->"

WORKER_GENERATED_MARKER = "Generated by `rite add worker`."


def mark_spec_section(section: str) -> str:
    return f"{SPEC_SECTION_START}\n{section.strip()}\n{SPEC_SECTION_END}"


def replace_spec_section(text: str, section: str, anchor: str) -> str | None:
    """`text` with its spec section replaced by `section`, which may be ""
    to remove it.

    A marked section is replaced between its markers. A file generated
    before the markers existed may carry a bare `## Project spec` heading,
    replaced up to the next `## ` heading; or no section at all, in which
    case one is inserted before `anchor`. Returns None when there is
    nowhere sensible to put it, so the caller reports that instead of
    appending the section somewhere nobody reads.
    """
    start = text.find(SPEC_SECTION_START)
    end = text.find(SPEC_SECTION_END)
    if start != -1 and end > start:
        new = text[:start] + section + text[end + len(SPEC_SECTION_END) :]
    else:
        legacy = text.find("\n## Project spec")
        if legacy != -1:
            nxt = text.find("\n## ", legacy + 1)
            if nxt != -1:
                nxt = back_over_marker(text, nxt)
            tail = "" if nxt == -1 else text[nxt + 1 :]
            new = text[: legacy + 1] + (section + "\n\n" if section else "") + tail
        elif not section:
            return text
        else:
            at = text.find("\n" + anchor)
            if at == -1:
                return None
            at = back_over_marker(text, at)
            new = text[: at + 1] + section + "\n\n" + text[at + 1 :]
    # Removing or re-sizing a section leaves the blank lines that framed it.
    return re.sub(r"\n{3,}", "\n\n", new)


@dataclass
class SpecState:
    """What is actually on disk, as opposed to what `config.yaml` claims."""

    present: list[str] = field(default_factory=list)  # registered, and there
    dangling: list[str] = field(default_factory=list)  # registered, nothing there
    unregistered_files: list[str] = field(default_factory=list)
    unregistered_dirs: list[str] = field(default_factory=list)


def spec_state(root: Path, config: ProjectConfig, module_paths: list[str]) -> SpecState:
    """The spec as the disk has it.

    A registered path with nothing behind it is not a spec, however
    confidently `config.yaml` names it. Unregistered candidates are looked
    for only when nothing registered exists, and split: a `SPEC.md` is a
    spec, while a `docs/` directory may or may not hold one, and treating
    it as one would send someone to register a folder of README fragments.
    """
    state = SpecState()
    for rel in config.spec.paths:
        (state.present if (root / rel).exists() else state.dangling).append(rel)
    if not state.present:
        from rite_ai.cli.init.detect import detect_spec_paths

        for rel in detect_spec_paths(root, module_paths):
            if rel in config.spec.paths:
                continue
            target = (
                state.unregistered_dirs
                if rel.endswith("/")
                else state.unregistered_files
            )
            target.append(rel)
    return state


# Below this, reading the spec whole is not a cost worth a command. Above it,
# `rite spec index` is the thing that ANSWERS the question — the notice
# deliberately does not claim the spec will decompose, because line count does
# not predict that: measured, a 606-line document decomposed and an 817-line
# one was refused.
_WORTH_ASKING_LINES = 500


def _digest_notice(root: Path, config: ProjectConfig) -> list[str]:
    """One line, once: that a registered spec is big enough to be worth asking
    about. Silent once the project has an index, so it cannot nag a project
    that has already answered the question either way."""
    from rite_ai.spec.index_file import index_path
    from rite_ai.spec.units import expand_paths

    if index_path(root).exists():
        return []
    files, _ = expand_paths(root, config.spec.paths)
    total = 0
    for rel in files:
        try:
            total += len((root / rel).read_text(encoding="utf-8").splitlines())
        except (OSError, UnicodeDecodeError):
            return []  # doctor reports an unreadable spec path itself
    if total < _WORTH_ASKING_LINES:
        return []
    where = files[0] if len(files) == 1 else f"{len(files)} files"
    return [
        f"spec: {where} is {total:,} lines — `rite spec index` says whether a "
        "Worker could load one part of it instead of all of it"
    ]


def spec_notices(
    root: Path, config: ProjectConfig, module_paths: list[str]
) -> list[str]:
    """What `rite doctor` says when no spec is registered.

    Reports only. Writing a spec is a session's work (`/spec`) and
    registering one is a command the user runs. A spec file that exists but
    is not registered is named, since that is what `/spec` leaves behind if
    the session stops before its last step. Configured paths, including
    missing ones, are reported by `doctor` itself.
    """
    if config.spec.paths:
        return _digest_notice(root, config)
    state = spec_state(root, config, module_paths)
    if state.unregistered_files:
        listed = ", ".join(state.unregistered_files)
        lines = [
            f"spec: {listed} exists but is not registered — Workers are not "
            f"pointed at it. `rite spec add {state.unregistered_files[0]}`"
        ]
    else:
        lines = [
            "spec: no project spec — run `/spec` in Claude Code to write one "
            "(or `rite spec add <path>` if it already exists)"
        ]
    for rel in state.unregistered_dirs:
        lines.append(
            f"spec: `{rel}` may hold design documents — "
            f"`rite spec add {rel}` if it does"
        )
    return lines


def orphaned_enrichment_notice(root: Path) -> str | None:
    """A `brief.yaml` still carrying the `enriched:` section earlier
    versions told the first session to append.

    Nothing parses it — `ProjectBrief` never had the field, and its only
    reader was the `reviewer-decisions` agent, which now reads the spec —
    so answers recorded there reach nobody. Said, with where they belong,
    rather than ignored.
    """
    try:
        raw = yaml.safe_load((root / ".rite" / "brief.yaml").read_text())
    except (OSError, yaml.YAMLError):
        return None
    if isinstance(raw, dict) and raw.get("enriched"):
        return (
            "brief.yaml has an `enriched:` section nothing reads — move its "
            "answers into the project spec, as decisions or open questions"
        )
    return None


@dataclass
class RefreshResult:
    updated: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)


def refresh_spec_sections(
    root: Path, config: ProjectConfig, *, apply: bool = True
) -> RefreshResult:
    """Rewrite the spec section of the Owner's and every Worker's generated
    `CLAUDE.md` to match `config.spec`.

    Without this, `rite init` was the only writer of the Owner's file, so a
    spec registered afterwards never reached the Owner, and a Worker created
    before it kept whatever init had found. A `CLAUDE.md` rite did not
    generate is left untouched and reported.

    `apply=False` reports what would change and writes nothing, which is what
    `rite update --files-only --dry-run` needs: this section is the one part
    of a generated file that refresh deliberately does not own, so asking it
    is the only way that command can tell the truth about the whole file.
    """
    from rite_ai.cli.init.claude_gen import GENERATED_MARKER
    from rite_ai.cli.init.claude_gen import _spec_section as owner_section
    from rite_ai.workspace.manage import (
        WORKER_MODULES_HEADING,
        WORKER_MODULES_HEADING_LEGACY,
        worker_spec_block,
    )

    targets = [
        (root / "CLAUDE.md", GENERATED_MARKER, owner_section(config), ("## Modules",))
    ]
    workers = root / "workers"
    if workers.is_dir():
        block = worker_spec_block(config.spec)
        for path in sorted(workers.glob("*/CLAUDE.md")):
            # Both spellings: the current heading, and the one every release
            # up to v0.3.0 wrote. A worker file generated before the rename
            # must still receive a spec added after it — that is the whole
            # point of this function, and keying it to one literal in a second
            # file is what broke when the heading changed.
            targets.append(
                (
                    path,
                    WORKER_GENERATED_MARKER,
                    block,
                    (WORKER_MODULES_HEADING, WORKER_MODULES_HEADING_LEGACY),
                )
            )

    result = RefreshResult()
    for path, marker, section, anchor in targets:
        rel = str(path.relative_to(root))
        try:
            text = path.read_text()
        except OSError:
            result.skipped.append(f"{rel}: not found")
            continue
        if marker not in text:
            result.skipped.append(f"{rel}: not generated by rite, left untouched")
            continue
        for candidate in anchor:
            new = replace_spec_section(text, section, candidate)
            if new is not None:
                break
        if new is None:
            names = " or ".join(f"`{a}`" for a in anchor)
            result.skipped.append(f"{rel}: no {names} heading to place it before")
            continue
        if new != text:
            if apply:
                write_atomic(path, new)
            result.updated.append(rel)
    return result
