"""Generated by `tools/template_history.py` — do not edit by hand.

SHA-256 of every command and agent template each tagged release shipped,
from: v0.1.0, v0.2.0, v0.3.0, v0.4.0, v0.5.0, v0.5.1.
"""

RELEASED: dict[str, frozenset[str]] = {
    "agents/reviewer-decisions.md": frozenset(
        {
            "1c4a28f3b2cb168f786e586cfd7b80d27739dfc7bb5fbe8e9905876839a6427c",
            "f06878fbfa708f08973b3a28cccc6cb052932b238eb54773d39cbf3df6c030ca",
        }
    ),
    "agents/reviewer-round1.md": frozenset(
        {
            "2fe030bf9fd00baeb0371d580419f708e6432fc01949ca728caefbb651cac362",
            "6fb7fe08d94c9b95eb028d83ed0f8871b678dbb324d8c5ea2b3df230d8596da4",
        }
    ),
    "agents/reviewer-seam.md": frozenset(
        {
            "c53463178ab6c55b004d8492fdb98dee952455e278bdac8334ac543f5c78d98d",
        }
    ),
    "agents/reviewer-terminating.md": frozenset(
        {
            "580014c22ed19ad3464705479092760cf8ad1a2fb9a65f843d6d55254bf68d8d",
        }
    ),
    "ci/publish-gate.yml": frozenset(
        {
            "3d198bd353c03a0d141030f39911b2e304c76f5861bba5711b905d7ff296809d",
            "5509db8ad3e4a554a94f9080193c47306f488320f829df88cf380be78534a08f",
            "a1ccd9ce36863a9367f9593be33b13509744d7cb3589e1c87a4601dbc3250f40",
            "a87b33135cd3dd28b98ff947b01452cb2e8bb9f4b1193144c0eed1be8de99f21",
            "e2266bd379218f9ca014740a6255120208edf64516ccc34a62999a918fe5b586",
            "ff1f67865f2fa62450cda8b6bf0be7f4531c3dd746cb537cd7a3fabb833d6b9f",
        }
    ),
    "commands/refine.md": frozenset(
        {
            "aced97a653ba7475e761746873f0194ec2bdd4c598ac7e0fa68b959bcd21dd59",
            "eae170352733d211087b9a45dbeecc5cd9aa8fa39850e3c7659e9ecb9748dcf4",
        }
    ),
    "commands/review.md": frozenset(
        {
            "26c8bdba0cd632db866f51ba37a3c580ecc1a832220cc3dc181eb69d708a2b9b",
            "4a649197bfeec27512646389995e6737e52430c1fdaadbbd483f1865ed958e8d",
            "bc6637d050c28a8b19f45522fd20f3fa7fb071e23b13e05e1304166d89588dde",
        }
    ),
    "commands/rite-start.md": frozenset(
        {
            "01e2ac698997946d882dc60d84647c1011d6c2028eb1705a08689424f876d811",
        }
    ),
    "commands/spec-digest.md": frozenset(
        {
            "5587947fb9078f018a67face57d52fd8e8ae2776cc60380e0df94f80af6c8399",
        }
    ),
    "commands/spec.md": frozenset(
        {
            "0506652dac22da8ab09bec1ff6647a317d74c7efe3e6b22a1ba0ccf8aad6fc4b",
        }
    ),
    "commands/ticket.md": frozenset(
        {
            "142dbf135366645a52d6e6c2b3184a7e15bcb8072da26f20aa25fb97ba9f953f",
            "1f6a0b73bed863680ad7e0b12c04b2d982c8d246845cd6489fc956ba4abf6df3",
        }
    ),
    "review-checklist.md": frozenset(
        {
            "3da56d0982170d8fe1de9579d5bb4c126b9b2f85e1834c9aa16c328c10501ede",
            "5efb3e9d1f0f6f3a1e2ae69a81c77843a1a8951f691178259bf3eeae8c22fc11",
            "d3f09181e42a11f5b70dcd5855d8a61b7583c8025d6af4d3f7a38cff36a259f5",
        }
    ),
}
