"""Regenerate `src/rite_ai/update/template_history.py` from every `v*` tag.

Run after tagging a release. `rite update` refreshes a copied command or agent
file only when its bytes match a version some release shipped; this table is
that list. A file that matches nothing released is the user's edit, and stays.
"""

from __future__ import annotations

import hashlib
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "rite_ai" / "update" / "template_history.py"


def _git(*args: str) -> bytes:
    return subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, check=True
    ).stdout


def _format(path: Path) -> None:
    """Hand the generated file to ruff.

    The emitter writes valid Python, not FORMATTED Python, so running this
    tool as `docs/releasing.md` step 5 says produced a file that fails
    `ruff format --check` — a red gate on the release commit, for a file
    nobody edits by hand. Measured after tagging v0.4.0.
    """
    subprocess.run(
        ["uv", "run", "ruff", "format", str(path)],
        cwd=ROOT,
        capture_output=True,
        check=False,
    )


def header(tags: list[str]) -> list[str]:
    """The generated file's docstring, its tag list wrapped to the line limit.

    ⚠ Wrapped because it grows with every release: the tenth tag, v0.7.0a3,
    took the one-line list to 91 characters, and `ruff check` (E501, 88) failed
    the post-tag commit. `ruff format` does not wrap a docstring, so the
    formatting step never caught it."""
    import textwrap

    listed = textwrap.wrap(f"from: {', '.join(tags)}.", width=88)
    return [
        '"""Generated by `tools/template_history.py` — do not edit by hand.',
        "",
        "SHA-256 of every command and agent template each tagged release shipped,",
        *listed,
        '"""',
    ]


def written_pin(tag: str) -> str:
    """The install pin `tag`'s own `rite init` wrote into the workflow.

    ⚠ **Not `@<tag>`.** `rite_install_spec` pins `v<VERSION>` only for a
    release-shaped VERSION and `main` for anything else, so every pre-release
    (0.7.0a1 to a6, and the plain tags a7 and a8 whose VERSION still reads
    0.7.0a6) wrote `@main`. Recorded as `@<tag>`, an alpha-built project's
    untouched workflow matched nothing, and upgrading it to 0.7.0 left it
    pinned to `main` and reported it as the user's edit
    (`test_upgrade_from_a_release`, at the 0.7.0 bump). The rule is the same
    at every tag since v0.1.0, so today's function answers for each."""
    from rite_ai.cli.init.scaffold import rite_install_spec

    return rite_install_spec(_git("show", f"{tag}:VERSION").decode().strip())


def main() -> None:
    tags = sorted(t for t in _git("tag", "-l", "v*").decode().split() if t)
    released: dict[str, set[str]] = {}
    for tag in tags:
        listing = _git(
            "ls-tree",
            "-r",
            "--name-only",
            tag,
            "--",
            "templates/commands",
            "templates/agents",
            "templates/review-checklist.md",
        )
        for path in listing.decode().split():
            data = _git("show", f"{tag}:{path}")
            key = path.removeprefix("templates/")
            released.setdefault(key, set()).add(hashlib.sha256(data).hexdigest())
        # The CI workflow is RENDERED, not copied: what a release wrote is its
        # template with that release's install pin substituted in. Recording
        # the rendered bytes is what lets a refresh tell an untouched workflow
        # — whose pin is now stale — from one the user has edited.
        try:
            template = _git("show", f"{tag}:templates/ci/publish-gate.yml").decode()
        except subprocess.CalledProcessError:
            continue
        rendered = template.replace("{{RITE_INSTALL_SPEC}}", written_pin(tag))
        released.setdefault("ci/publish-gate.yml", set()).add(
            hashlib.sha256(rendered.encode()).hexdigest()
        )
    lines = [*header(tags), "", "RELEASED: dict[str, frozenset[str]] = {"]
    for key in sorted(released):
        lines.append(f"    {key!r}: frozenset(")
        lines.append("        {")
        for digest in sorted(released[key]):
            lines.append(f"            {digest!r},")
        lines.append("        }")
        lines.append("    ),")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n")
    _format(OUT)
    print(f"wrote {OUT.relative_to(ROOT)} from {len(tags)} tag(s)")


if __name__ == "__main__":
    main()
