"""Regenerate `src/rite_ai/update/template_history.py` from every `v*` tag.

Run after tagging a release. `rite update` refreshes a copied command or agent
file only when its bytes match a version some release shipped; this table is
that list. A file that matches nothing released is the user's edit, and stays.
"""

from __future__ import annotations

import hashlib
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "rite_ai" / "update" / "template_history.py"


def _git(*args: str) -> bytes:
    return subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, check=True
    ).stdout


def main() -> None:
    tags = sorted(t for t in _git("tag", "-l", "v*").decode().split() if t)
    released: dict[str, set[str]] = {}
    for tag in tags:
        listing = _git(
            "ls-tree",
            "-r",
            "--name-only",
            tag,
            "--",
            "templates/commands",
            "templates/agents",
            "templates/review-checklist.md",
        )
        for path in listing.decode().split():
            data = _git("show", f"{tag}:{path}")
            key = path.removeprefix("templates/")
            released.setdefault(key, set()).add(hashlib.sha256(data).hexdigest())
        # The CI workflow is RENDERED, not copied: what a release wrote is its
        # template with that release's install pin substituted in. Recording
        # the rendered bytes is what lets a refresh tell an untouched workflow
        # — whose pin is now stale — from one the user has edited.
        try:
            template = _git("show", f"{tag}:templates/ci/publish-gate.yml").decode()
        except subprocess.CalledProcessError:
            continue
        rendered = template.replace(
            "{{RITE_INSTALL_SPEC}}",
            f"git+https://github.com/robbartoszewski/rite.git@{tag}",
        )
        released.setdefault("ci/publish-gate.yml", set()).add(
            hashlib.sha256(rendered.encode()).hexdigest()
        )
    lines = [
        '"""Generated by `tools/template_history.py` — do not edit by hand.',
        "",
        "SHA-256 of every command and agent template each tagged release shipped,",
        f"from: {', '.join(tags)}.",
        '"""',
        "",
        "RELEASED: dict[str, frozenset[str]] = {",
    ]
    for key in sorted(released):
        lines.append(f"    {key!r}: frozenset(")
        lines.append("        {")
        for digest in sorted(released[key]):
            lines.append(f"            {digest!r},")
        lines.append("        }")
        lines.append("    ),")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} from {len(tags)} tag(s)")


if __name__ == "__main__":
    main()
