"""Generate `CLAUDE.md` and `.claude/` from the answers `rite init` collected.

SPEC.md §9.4.3 draws the line: the **templated** layer (role structure, the
review convention, claims, the ticket workflow, the publish gate) is
identical across every rite project and lives in `templates/agents/` and
`templates/commands/` verbatim. The **derived** layer (module map, commands,
architecture notes) is built here from `brief.yaml` / `modules.yaml` /
`config.yaml` — best-effort from detection, never invented. Where nothing was
detected, the placeholder says so explicitly, because a confidently wrong
build command poisons every session that inherits it.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from rite_ai.config.models import Module, ProjectBrief, ProjectConfig, SandboxConfig

from .detect import ModuleCommands, module_commands
from .paths import templates_dir

_AGENT_FILES = [
    "reviewer-round1.md",
    "reviewer-terminating.md",
    "reviewer-seam.md",
    "reviewer-decisions.md",
]
_COMMAND_FILES = ["ticket.md", "review.md", "refine.md"]


# The line every generated `CLAUDE.md` carries, and the only way to tell
# rite's own output from something a human wrote.
GENERATED_MARKER = "Generated by `rite init`."


def preserve_foreign_claude_md(project_root: Path) -> Path | None:
    """Move an existing, human-authored `CLAUDE.md` aside. Returns where it
    went, or None if there was nothing to preserve.

    This was a bare `write_text`: `rite init` replaced whatever `CLAUDE.md`
    it found, with no prompt, no backup and exit 0. The directory that gets
    hit is the ordinary one — an existing repository adopting rite, which
    has a `CLAUDE.md` and no `.rite/` — because `init` refuses outright
    once `.rite/` exists, so the only reachable path is the first run, on a
    project that already had standing instructions. The dogfood guide
    carries it as its first ⛔ STOP, against a 77 KB file that is what
    every live session on that machine loads.

    A file rite generated itself is overwritten without ceremony; that is
    regeneration, not destruction, and it is told apart by the marker
    rather than by who ran the command.

    Preserved rather than refused, unlike `rite remove worker`: writing
    `CLAUDE.md` is what `init` is FOR, and refusing would mean rite could
    never initialise a repository that already had one — the common case.
    Nothing is destroyed either way, which is the property that matters.
    """
    existing = project_root / "CLAUDE.md"
    if not existing.is_file():
        return None
    try:
        if GENERATED_MARKER in existing.read_text():
            return None
    except OSError:
        # Unreadable is not "ours". Preserve it; the one thing this must
        # never do is delete a file it could not look at.
        pass
    target = project_root / "CLAUDE.md.pre-rite"
    counter = 2
    while target.exists():
        target = project_root / f"CLAUDE.md.pre-rite.{counter}"
        counter += 1
    existing.rename(target)
    return target


def install_claude_config(
    project_root: Path,
    role: str,
    brief: ProjectBrief,
    modules: list[Module],
    config: ProjectConfig,
) -> dict[str, object]:
    """Write CLAUDE.md, .claude/agents/*, .claude/commands/*. Returns counts.

    `preserved` in the returned dict is 1 when an existing, human-authored
    `CLAUDE.md` was moved aside — the caller reports where it went.
    """
    preserved = preserve_foreign_claude_md(project_root)
    claude_md = generate_claude_md(role, brief, modules, config, project_root)
    (project_root / "CLAUDE.md").write_text(claude_md)

    agents_dir = project_root / ".claude" / "agents"
    commands_dir = project_root / ".claude" / "commands"
    agents_dir.mkdir(parents=True, exist_ok=True)
    commands_dir.mkdir(parents=True, exist_ok=True)

    src_templates = templates_dir()
    for fname in _AGENT_FILES:
        shutil.copyfile(src_templates / "agents" / fname, agents_dir / fname)
    for fname in _COMMAND_FILES:
        shutil.copyfile(src_templates / "commands" / fname, commands_dir / fname)

    return {
        "agents": len(_AGENT_FILES),
        "commands": len(_COMMAND_FILES),
        "preserved": str(preserved) if preserved else "",
    }


def generate_claude_md(
    role: str,
    brief: ProjectBrief,
    modules: list[Module],
    config: ProjectConfig,
    project_root: Path,
) -> str:
    if role not in ("owner", "manager"):
        raise ValueError(f"unknown role: {role!r}")

    parts = [
        _header(brief),
        _startup_section(),
        _what_this_is(brief),
        _spec_section(config),
        _modules_section(modules, project_root, config.sandbox),
        _role_section(role, config),
        _ticket_workflow_section(),
        _claims_section(),
        _review_section(),
        _publish_gate_section(),
        _knowledge_section(),
        _commands_section(),
    ]
    return "\n\n".join(p.strip() for p in parts) + "\n"


def _spec_section(config: ProjectConfig) -> str:
    """Where the project's own design lives — paths, never content.

    The same pointer a Worker gets, because a Manager writing tickets that
    cite decisions needs to reach the register those numbers refer to.
    Empty when no spec is configured, rather than a heading explaining
    that there is nothing under it."""
    spec = config.spec
    if not spec.paths:
        return ""
    listed = "\n".join(f"- `{p}`" for p in spec.paths)
    convention = f"\n{spec.convention}\n" if spec.convention else ""
    return f"""## Project spec

This project's design lives in:

{listed}

Point Workers at it in tickets rather than restating it; read what you need
rather than all of it.
{convention}
rite cannot tell whether this is current. If it contradicts the code, say so
in the ticket rather than silently implementing either."""


def _header(brief: ProjectBrief) -> str:
    role_label = "Owner" if brief.role == "owner" else "Manager"
    article = "an" if role_label == "Owner" else "a"
    return f"""\
# CLAUDE.md — {brief.name}

Generated by `rite init`. This machine is {article} **{role_label}** (SPEC.md §2).
Root branch: `{brief.root_branch or "main"}`.

This file carries only the coordination basics. Project-specific knowledge —
database conventions, API patterns, architecture decisions, domain rules —
lives in `.rite/context/`, indexed by `.rite/context/INDEX.md`. Read the
index before assuming this file has everything."""


def _startup_section() -> str:
    return """\
## Before anything else: read the handover snapshot

Run `rite handover show` before evaluating what to do next. A fresh session
has no memory of what the previous one was doing — the snapshot is where
that state actually lives (SPEC.md §9.10.1). If it shows an in-progress
ticket, next step, or open blocker, start from there rather than
re-deriving it. An empty or missing snapshot just means nothing was
recorded yet — proceed to `rite start`'s orientation table as normal."""


def _what_this_is(brief: ProjectBrief) -> str:
    kind = brief.kind or "(not specified — ask in the first session)"
    features = (
        brief.features or "_Not described yet — ask the user what this project does._"
    )
    tech_bits = []
    if brief.platform:
        tech_bits.append(f"platform: {brief.platform}")
    if brief.languages:
        tech_bits.append(f"languages: {', '.join(brief.languages)}")
    if brief.frameworks:
        tech_bits.append(f"frameworks: {', '.join(brief.frameworks)}")
    tech_line = "; ".join(tech_bits) if tech_bits else "not specified"

    architecture = (
        brief.architecture
        or "_Not specified. If this project has an architectural pattern "
        "(event sourcing, CQRS, microservices, monolith) worth naming, ask "
        "and record it in `.rite/brief.yaml` under `technology.architecture`, "
        "or as a file under `.rite/context/`._"
    )

    return f"""\
## What this is

**Kind:** {kind}

{features}

**Technology:** {tech_line}

**Architecture:** {architecture}"""


def _modules_section(
    modules: list[Module], project_root: Path, sandbox: SandboxConfig
) -> str:
    if not modules:
        return """\
## Modules

No modules registered yet. Register one with `rite add module <name> \
[git-url]`, or hand-edit `.rite/modules.yaml`."""

    rows = ["## Modules", ""]
    for m in modules:
        rows.append(f"### `{m.path}` — {m.name}")
        if m.description:
            rows.append(m.description)
        rows.append(
            f"Branch: `{m.branch}`" + (f" · {m.url}" if m.url else " · local only")
        )
        rows.append("")
        cmds = module_commands(m, project_root, sandbox)
        rows.extend(_format_commands(cmds))
        rows.append("")
    return "\n".join(rows)


def _format_commands(cmds: ModuleCommands) -> list[str]:
    if not cmds.detected:
        lines = [
            "- Commands: not detected. Record them in `.rite/modules.yaml` under "
            "this module's `commands:` (install, build, test, lint, format) — ask "
            "the user, or read the module to find them. Do not guess."
        ]
        if cmds.note:
            lines.append(f"- Why: {cmds.note}")
        return lines
    lines = []
    for label, key in (
        ("Install", "install"),
        ("Build", "build"),
        ("Test", "test"),
        ("Lint", "lint"),
        ("Format", "format"),
    ):
        value = getattr(cmds, key)
        if value:
            where = " (recorded in modules.yaml)" if key in cmds.configured else ""
            lines.append(f"- {label}: `{value}`{where}")
        else:
            lines.append(
                f"- {label}: not detected in {cmds.source} — record it under "
                "`commands:` in `.rite/modules.yaml`, don't guess."
            )
    if cmds.note:
        lines.append(f"- Note: {cmds.note}")
    return lines


def _role_section(role: str, config: ProjectConfig) -> str:
    tb = config.ticket_backend
    if tb.type == "none":
        backend_line = (
            "No ticket backend configured. Set one in `.rite/config.yaml` "
            "(`ticket_backend.type: jira | github`), or work directly with "
            "`rite status` / `rite claim` without a board."
        )
    elif tb.type == "jira":
        backend_line = (
            f"JIRA at `{tb.site or '(site not set — fill in .rite/config.yaml)'}`. "
            "Board/project keys are not yet set in `.rite/config.yaml` under "
            "`ticket_backend.projects` — fill those in before relying on "
            "automation that needs them (SPEC.md §6.2)."
        )
    else:
        backend_line = "GitHub Issues, via the `gh` CLI (SPEC.md §6.3)."

    if role == "owner":
        expertise_lines = []
        if config.expertise:
            expertise_lines.append("**Expertise routing:**")
            for e in config.expertise:
                expertise_lines.append(f"- {e.name}: {', '.join(e.tags)}")
        else:
            expertise_lines.append(
                "**Expertise routing:** not configured. Add entries under "
                "`expertise:` in `.rite/config.yaml` to route decisions by tag "
                "(SPEC.md §4); until then, decisions default to you."
            )
        return f"""\
## Role: Owner

You own the board and the project-wide ticket queue (SPEC.md §2.3): assign
work, monitor blocked and stalled tickets, and make project-wide calls that
a Worker or Manager shouldn't make alone.

**Workers are interchangeable, and a Worker is a workspace — not a module,
a component or a specialism** (SPEC.md §5.3.4). `workers/<name>/` holds its
own checkout of every module, and every Worker carries the same project
credentials, so any Worker can take any ticket. Assign by who is free, and
never keep one Worker per module: two Workers editing different files of the
same module at once is normal, and `rite claim` on the paths is what keeps
them apart. Naming Workers after modules is the mistake this note exists to
prevent — it makes half of them idle while the rest queue.

**Ticket backend:** {backend_line}

{chr(10).join(expertise_lines)}"""

    return f"""\
## Role: Manager

You dispatch work to your own Workers and defer to the Owner on project-wide
matters (SPEC.md §2.2). You do not see or control another Manager's Workers.

**Workers are interchangeable, and a Worker is a workspace — not a module,
a component or a specialism** (SPEC.md §5.3.4). Assign by who is free, never
one Worker per module; `rite claim` on the paths is what keeps two Workers
out of each other's way.

**Workers:** none yet. Add one with `rite add worker <name>` — it creates
`workers/<name>/` with its own checkouts and its own scoped instructions.

**Ticket backend:** {backend_line}"""


def _ticket_workflow_section() -> str:
    return """\
## Ticket workflow

Claim → work → run the module's tests and lint → verify your own fix →
review → PR → merge → release. See `/ticket` for the full sequence. A Worker
behaves like a real developer: pulls before committing, opens PRs, merges
reviewed work — it does not push straight to the root branch.

The test and lint commands are the `Test:` and `Lint:` lines in the module
map above, read out of each module's own manifest by `rite init`. Run them as
written rather than inventing one; where a line says "not detected", ask. A
command that is wrong in a way that still exits 0 is indistinguishable from a
passing suite."""


def _claims_section() -> str:
    return """\
## Claims system

Before touching a path, claim it:

```
rite claim <paths...> --worker <name> --ticket <id>
rite release --worker <name>
```

Claims are checked at file or directory granularity — never a whole module,
which would serialise unrelated work (SPEC.md §5.2). A claim that overlaps
another session's is refused; do not work around a refusal by claiming a
narrower or wider path to dodge the check.

While you hold a claim, beat:

```
rite heartbeat --worker <name> --ticket <id>
```

Every ten minutes or so, for as long as you are working. This is the only
thing that writes the liveness record `rite watchdog` and `rite status`
read — a Worker that never beats is reported STALLED, and the watchdog will
keep waking a human about it (SPEC.md §9.8)."""


def _review_section() -> str:
    return """\
## Review convention

Two stages (SPEC.md §7, `/review`):

1. **Round 1** — independent, fresh-eyes agents (`reviewer-round1`) against
   the checklist `rite review` prints (`rite review --module <name>` appends
   that repo's own to the project-wide one — don't merge the two by hand).
   For anything crossing a module boundary, also run `reviewer-seam`. Fix
   what they find.
2. **The terminating check** — fresh `reviewer-terminating` agents scoped to
   round 1's *fixes*, not its findings. This is the last stage; there is no
   round 3.

A finding without a recorded reason for its fix — evidence: a failing test,
a killed mutant, or "not measurable here, because…" — is not resolved, it's
asserted. Keep the register."""


def _publish_gate_section() -> str:
    return """\
## Publish gate

`rite publish check` scans all committed content — source, docs, comments,
test fixtures, file names — for secrets and hardcoded local paths (SPEC.md
§11).

Two layers run it for you, and **neither is guaranteed to be here**: a
pre-push hook, which `rite init` installs only where git will actually read
it (`core.hooksPath` silently redirects hooks wholesale), and
`.github/workflows/publish-gate.yml`, which is the layer no local git config
can switch off (§11.5.1) and is therefore the one that matters. `rite doctor`
reports the hook; `rite publish install-hook` and `rite publish install-ci`
add either one to a project that has none. Do not assume either is armed —
a gate that reports itself installed while being inactive is the worst shape
a defect in this tool takes.

`.rite/kb/` is scanned hardest: it is where proprietary and niche
material lives, and it is committed to the repo, so anything that shouldn't
leave the team must not be copied there without checking §8.7 first.

A finding that's genuinely safe gets a one-line suppression with a reason,
never a blanket off switch."""


def _knowledge_section() -> str:
    return """\
## Project knowledge

- `.rite/context/INDEX.md` — project-specific conventions, architecture
  decisions, domain rules. Check the "when to consult" column before
  assuming a topic isn't covered.
- `.rite/kb/INDEX.md` — user-provided reference material: coding standards,
  algorithms, domain knowledge. Authored files are committed; fetched link
  caches are gitignored and populated with `rite kb refresh`.

Both are pointers, not embedded content — read the index, then the specific
file you need. Do not paste `context/` or `kb/` content into this file."""


def _commands_section() -> str:
    return """\
## Commands

- `/ticket <id>` — work a ticket end to end.
- `/review` — run the review convention over the current change.
- `/refine <ticket-or-phrase>` — turn a ticket or a vague phrase into
  something startable cold. Implements nothing.

This file was generated by `rite init` from `.rite/brief.yaml`,
`.rite/modules.yaml`, and `.rite/config.yaml`. The first Claude session
should read `brief.yaml` and ask the two or three follow-ups the answers
actually warrant, appending to the same file (SPEC.md §8.1) — this is
expected, not a sign the questionnaire was incomplete."""


__all__ = ["install_claude_config", "generate_claude_md"]
