"""Multi-project registry — the Dispatch directory (SPEC §8.9, D-34).

Additive only: a single-project setup needs none of this. `~/.rite/
dispatch/` is owned by the human's Dispatch hub, not by any project — it
is a lookup table over directories ("addressing only, never live state"),
never a hierarchy replacing them. A project's own `.rite/` is completely
unaware the registry exists; nothing here reaches INTO a project except to
read its `config.yaml` for the aggregate-load warning (§2.7.4), which is
read-only.

`~/.rite/dispatch/` (created lazily by `rite projects add` — there is no
`rite dispatch init`; the first `add` scaffolds it):

    ~/.rite/dispatch/
    ├── CLAUDE.md        # hub instructions — thin, generated once
    └── projects.yaml    # the registry

⚠ There is no hub `config.yaml`. This docstring listed one, "currently
just the warning threshold", and nothing ever created or read it — the
threshold is `aggregate_load_warning`'s `threshold_pct` default and no
caller passes anything else. Documented as absent rather than invented:
a file the docs promise and the code never writes is worse than a fixed
default that says it is one.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path

import yaml


def default_dispatch_dir() -> Path:
    """`~/.rite/dispatch/`, overridable via `RITE_DISPATCH_DIR` — a
    function, not a module-level constant, specifically so tests can
    redirect it with `monkeypatch.setenv` instead of writing to the real
    machine's home directory every time a CLI test touches the registry."""
    override = os.environ.get("RITE_DISPATCH_DIR")
    return Path(override) if override else Path.home() / ".rite" / "dispatch"


_HUB_CLAUDE_MD = """\
# CLAUDE.md — Dispatch hub

Generated by `rite projects add`. This is NOT a project — it is the
registry of projects on this machine (SPEC.md §8.9).

Spawn or attach to a per-project Manager rather than holding project
context here yourself (§8.6.1: a hub that accumulates every project's
detail pays the same context-growth cost a single overloaded Manager
does). `rite projects list` shows what is registered; `rite start
<alias>` brings one up.
"""


@dataclass
class ProjectEntry:
    alias: str
    path: str
    role: str = "manager"  # this machine's role for THIS project


@dataclass
class Registry:
    projects: dict[str, ProjectEntry] = field(default_factory=dict)


@dataclass
class DispatchResult:
    ok: bool
    message: str = ""


def _registry_path(dispatch_dir: Path) -> Path:
    return dispatch_dir / "projects.yaml"


def load_registry(dispatch_dir: Path) -> Registry:
    path = _registry_path(dispatch_dir)
    if not path.is_file():
        return Registry()
    try:
        raw = yaml.safe_load(path.read_text()) or {}
    except yaml.YAMLError:
        return Registry()
    projects_raw = raw.get("projects", {}) if isinstance(raw, dict) else {}
    projects = {}
    if isinstance(projects_raw, dict):
        for alias, entry in projects_raw.items():
            if isinstance(entry, dict):
                projects[alias] = ProjectEntry(
                    alias=alias,
                    path=entry.get("path", ""),
                    role=entry.get("role", "manager"),
                )
    return Registry(projects=projects)


def _locked_registry(dispatch_dir: Path):
    """Exclusion around the registry's read-modify-write.

    `add_project` and `remove_project` both read the whole registry,
    change one entry and write it all back, unlocked and with a
    truncating write. Measured, six concurrent registrations over five
    rounds: every round lost entries and the worst kept one of six."""
    from rite_ai.state import locked

    return locked(_registry_path(dispatch_dir))


def save_registry(dispatch_dir: Path, registry: Registry) -> None:
    dispatch_dir.mkdir(parents=True, exist_ok=True)
    claude_md = dispatch_dir / "CLAUDE.md"
    if not claude_md.is_file():
        from rite_ai.state import write_atomic as _wa

        _wa(claude_md, _HUB_CLAUDE_MD)
    data = {
        "projects": {
            alias: {"path": entry.path, "role": entry.role}
            for alias, entry in registry.projects.items()
        }
    }
    from rite_ai.state import write_atomic

    write_atomic(
        _registry_path(dispatch_dir),
        yaml.safe_dump(data, sort_keys=False, default_flow_style=False),
    )


def add_project(
    dispatch_dir: Path, alias: str, path: Path, role: str = "manager"
) -> DispatchResult:
    dispatch_dir.mkdir(parents=True, exist_ok=True)
    with _locked_registry(dispatch_dir):
        registry = load_registry(dispatch_dir)
        if alias in registry.projects:
            return DispatchResult(False, f"alias '{alias}' already registered")
        registry.projects[alias] = ProjectEntry(
            alias=alias, path=str(path.resolve()), role=role
        )
        save_registry(dispatch_dir, registry)
    # The RESOLVED path, which is what was stored. `rite projects add
    # sched .` used to confirm "registered 'sched' -> .", which tells the
    # user nothing about which directory is now in the registry — and
    # registering the wrong directory is the mistake this line exists to
    # let them catch.
    return DispatchResult(True, f"registered '{alias}' -> {path.resolve()}")


def remove_project(dispatch_dir: Path, alias: str) -> DispatchResult:
    dispatch_dir.mkdir(parents=True, exist_ok=True)
    with _locked_registry(dispatch_dir):
        registry = load_registry(dispatch_dir)
        if alias not in registry.projects:
            return DispatchResult(False, f"no such alias: '{alias}'")
        del registry.projects[alias]
        save_registry(dispatch_dir, registry)
    return DispatchResult(True, f"deregistered '{alias}' (files untouched)")


def resolve_alias(dispatch_dir: Path, alias: str) -> Path | None:
    """An alias resolves to a `path` the same way a bare `rite start .`
    resolves to the current directory — this is a lookup, not a new
    lifecycle mechanism."""
    registry = load_registry(dispatch_dir)
    entry = registry.projects.get(alias)
    return Path(entry.path) if entry else None


def aggregate_load_warning(
    dispatch_dir: Path, registry: Registry | None = None, threshold_pct: int = 100
) -> str | None:
    """Sum each registered project's OWN `budget.weekly_quota_pct` and warn
    if the total exceeds `threshold_pct`. Returns `None` when there's
    nothing to warn about.

    **This is a sum of configured intentions, not a projection of measured
    use, and it cannot become one.** An earlier version of this docstring
    said the real formula was merely unbuilt — "no burn-rate-measurement
    module exists in this codebase yet". That is now wrong twice over:
    `rite_ai.budget` shipped in P1.14c and does measure real consumption
    from Claude Code transcripts; and the projection §2.7.4 described was
    never buildable from it anyway.

    The reason is the same one §2.6.2 records for dropping the per-project
    percentage: **per-project attribution does not exist.** Anthropic's
    weekly quota is account-wide, a session can be run against any project
    from any working directory, and per-worker sessions write their own
    transcript directories. `budget.read_usage_since` therefore reports one
    machine-wide number — real, but not divisible by project, which is
    exactly the input "each registered project's recent burn-rate history"
    would require. Measuring harder does not recover it.

    So this stays a heuristic, and §2.7.4 was amended to describe a
    heuristic rather than leaving a formula standing that reads as merely
    not-done-yet. What it is good for is unchanged and worth keeping: three
    projects each configured for 50% of the week sum to 150%, and that is a
    real misconfiguration visible at `projects add` time, before any quota
    is spent. What it must never do is imply the sum was measured."""
    registry = registry if registry is not None else load_registry(dispatch_dir)
    if not registry.projects:
        return None

    # Only projects that actually SET the key are summed.
    #
    # `parse_config` fills in `weekly_quota_pct` from its dataclass
    # default (95), and the sum used to include those — so two projects
    # that had never heard of the key produced "budget.weekly_quota_pct
    # sum to 190% (one=95%, two=95%) ... independently-configured
    # targets", naming a setting neither config file contained. Measured:
    # the warning fired on the SECOND project of every registry,
    # unconditionally, whatever anyone had configured. A warning that
    # cannot not fire is one nobody reads.
    configured: list[tuple[str, int]] = []
    unset: list[str] = []
    for alias, entry in registry.projects.items():
        pct = _configured_quota_pct(Path(entry.path))
        if pct is None:
            unset.append(alias)
        else:
            configured.append((alias, pct))

    # One configured target cannot conflict with anything; the point of
    # this warning is targets that add up across projects.
    if len(configured) < 2:
        return None

    total = sum(pct for _, pct in configured)
    if total <= threshold_pct:
        return None

    per_project = ", ".join(f"{alias}={pct}%" for alias, pct in configured)
    note = ""
    if unset:
        note = (
            f" ({len(unset)} other registered project(s) set no target, so "
            "they are not counted here)"
        )
    return (
        f"registered projects' budget.weekly_quota_pct sum to {total}% "
        f"({per_project}){note} — over {threshold_pct}% even before "
        "accounting for any single project running over its own target. "
        "This is a sum of what you configured, not a measurement: quota is "
        "account-wide, so no per-project rate exists to project from "
        "(§2.6.2). Treat it as a heads-up to check your own schedules, not "
        "a hard limit. `rite budget` reports the real machine-wide rate."
    )


def _configured_quota_pct(project_root: Path) -> int | None:
    """`budget.weekly_quota_pct` as WRITTEN in a project's config, or None
    when the project does not set it.

    Read from the raw YAML rather than through `parse_config`, which
    cannot express the difference: it returns the dataclass default for an
    absent key, and "the user chose 95" and "nobody chose anything" are
    different facts to a function whose whole job is warning about what
    users chose."""
    config_path = project_root / ".rite" / "config.yaml"
    if not config_path.is_file():
        return None
    try:
        raw = yaml.safe_load(config_path.read_text())
    except (yaml.YAMLError, OSError):
        return None
    if not isinstance(raw, dict):
        return None
    budget = raw.get("budget")
    if not isinstance(budget, dict):
        return None
    pct = budget.get("weekly_quota_pct")
    return pct if isinstance(pct, int) and not isinstance(pct, bool) else None
