"""Derived unit files, and whether they still match the spec.

`/spec-digest` writes one file per derived unit under `.rite/spec/units/`:

    <!-- GENERATED by /spec-digest. DO NOT EDIT: change the spec, then re-digest. -->
    ---
    id: 2.4/promotion
    covers: [2.4/promotion]
    source: SPEC.md
    source_sha: 3f1c…   # stamped
    body_sha: 9a02…     # stamped
    ---
    <the derived text>

**Hashes are stamped by `rite spec stamp`, never typed.** A session writes the
body and `covers`, then stamps; the stamp records a hash of the source units
the file covers and a hash of its own body. Stamping is a deliberate step, not
something `rite spec index` does on every run, because an automatic restamp
would bless both a source change (nothing would ever read as stale) and a
hand-edit (nothing would ever read as tampered).

What the status finds, per the design's gate:

* **new** — a source unit no derived file covers;
* **stale** — the source a file covers changed since it was stamped;
* **removed** — a file covers a unit the source no longer has;
* **tampered** — a file's body no longer matches its stamped hash;
* **unstamped** — written and never stamped;
* **unreadable** — a file that cannot be parsed as a unit file at all, reported
  by name rather than skipped.

Index sections are not expected to be covered: nobody's ticket is an index.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from rite_ai.spec.graph import INDEX
from rite_ai.spec.units import Unit
from rite_ai.state import write_atomic

UNITS_DIR = Path(".rite") / "spec" / "units"
BANNER = (
    "<!-- GENERATED by /spec-digest. DO NOT EDIT: change the spec, then re-digest. -->"
)
_FRONT_MATTER = re.compile(r"\A(?:<!--.*?-->\s*\n)?---\n(.*?)\n---\n?(.*)\Z", re.S)


@dataclass(frozen=True)
class UnitFile:
    path: Path
    id: str
    covers: tuple[str, ...]
    source: str
    source_sha: str
    body_sha: str
    body: str


@dataclass
class DigestStatus:
    new: list[str] = field(default_factory=list)
    stale: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    tampered: list[str] = field(default_factory=list)
    unstamped: list[str] = field(default_factory=list)
    unreadable: list[str] = field(default_factory=list)
    # Two derived files covering one source unit. NOT part of `clean`: merging
    # and splitting units is allowed, so an overlap is a question ("which of
    # these two does a Worker get?"), not a defect. `rite spec verify --strict`
    # is where it becomes one.
    overlapping: list[str] = field(default_factory=list)
    files: int = 0

    @property
    def clean(self) -> bool:
        return not (
            self.new
            or self.stale
            or self.removed
            or self.tampered
            or self.unstamped
            or self.unreadable
        )


def units_dir(root: Path) -> Path:
    return root / UNITS_DIR


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# Long enough to stay readable, short enough that the name plus a digest and
# `.md` clears the 255-byte limit every common file system has.
_NAME_BUDGET = 120


def unit_filename(unit_id: str) -> str:
    """A file name for a unit id. DIFFERENT IDS NEVER SHARE ONE.

    Ids hold characters a path should not: `/` (slug paths), `#` (a unit from a
    later spec file), `~` (a duplicate heading), and anything a heading in any
    language puts in a slug. Each becomes `_<hex>_`, `_` itself included.

    The delimiters are the point. `_{ord:02x}` without one is not prefix-free
    beyond U+00FF: `āa` (U+0101 then `a`) and `ယ` (U+101A) both render `_101a`,
    so two units would land on one file and the first would be overwritten by
    the second, silently and unrecoverably — status would go on reporting a
    unit as missing at a path that already exists.

    A name over the budget keeps a readable head and ends in a hash of the
    whole id, because a spec with 60-character headings should not produce a
    file nobody can write.
    """
    safe = re.sub(r"[^A-Za-z0-9.-]", lambda m: f"_{ord(m.group()):x}_", unit_id)
    if len(safe) > _NAME_BUDGET:
        safe = safe[: _NAME_BUDGET - 17] + "-" + _sha(unit_id)[:16]
    return safe + ".md"


def body_hash(
    body: str, unit_id: str = "", covers: tuple[str, ...] = (), source: str = ""
) -> str:
    """What `body_sha` records: the file as written, minus the two stamp fields.

    The front matter is inside it because it is not decoration — `covers` is
    what the source hash is computed over, `id` is how the file is addressed.
    While only the body was hashed, editing `covers` by hand reported the file
    as STALE ("the spec changed under it", which it had not) and editing `id`
    or `source` reported nothing at all, on a file whose first line says DO NOT
    EDIT.
    """
    head = (
        f"{unit_id}\n{','.join(covers)}\n{source}\n"
        if unit_id or covers or source
        else ""
    )
    return _sha(head + body.replace("\r\n", "\n").strip() + "\n")


def file_hash(unit_file: UnitFile) -> str:
    return body_hash(unit_file.body, unit_file.id, unit_file.covers, unit_file.source)


def covers_hash(units: dict[str, Unit], covers: tuple[str, ...]) -> str | None:
    """A hash of the source units a file covers, or None if one is missing."""
    if not covers or any(c not in units for c in covers):
        return None
    return _sha("\n".join(f"{c}:{units[c].sha}" for c in sorted(covers)))


def render_unit_file(
    unit_id: str,
    covers: tuple[str, ...],
    source: str,
    source_sha: str,
    body_sha: str,
    body: str,
) -> str:
    meta = {
        "id": unit_id,
        "covers": list(covers),
        "source": source,
        "source_sha": source_sha,
        "body_sha": body_sha,
    }
    front = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True).strip()
    return f"{BANNER}\n---\n{front}\n---\n{body.strip()}\n"


def _unquoted(value) -> bool:
    """A unit id YAML has already turned into a number."""
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def _quote_it(path: Path, field_name: str, value) -> str:
    """Refused rather than coerced. `id: 8.10` is the number 8.1, and 8.1 is a
    DIFFERENT section of the spec — writing str(8.1) back would point the
    derived file at the wrong unit and nothing downstream could tell.

    Which is why the fix cannot name `value`: by the time this runs, `8.10` is
    already gone. Telling the reader to "write it as '8.1'" would hand them the
    wrong section with a straight face."""
    return (
        f"{path.name}: {field_name} must be quoted — YAML read it as the number "
        f"{value!r}, losing how the spec writes it (unquoted, 8.10 becomes 8.1, "
        "which is another section). Quote it exactly as the spec numbers it: "
        f"{field_name}: '<id>'"
    )


def read_unit_file(path: Path) -> UnitFile | str:
    """The unit file at `path`, or a message saying why it is not one."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as e:
        return f"{path.name}: cannot be read ({e})"
    m = _FRONT_MATTER.match(text.replace("\r\n", "\n"))
    if not m:
        return f"{path.name}: no front matter between --- lines"
    try:
        meta = yaml.safe_load(m.group(1))
    except yaml.YAMLError as e:
        return f"{path.name}: front matter is not YAML ({e})"
    if not isinstance(meta, dict):
        return f"{path.name}: front matter is not a mapping"
    unit_id, covers = meta.get("id"), meta.get("covers")
    if _unquoted(unit_id):
        return _quote_it(path, "id", unit_id)
    if not isinstance(unit_id, str) or not unit_id.strip():
        return f"{path.name}: no id"
    if isinstance(covers, list):
        loose = next((c for c in covers if _unquoted(c)), None)
        if loose is not None:
            return _quote_it(path, "covers", loose)
    if (
        not isinstance(covers, list)
        or not covers
        or not all(isinstance(c, str) and c for c in covers)
    ):
        return f"{path.name}: 'covers' must list the source unit ids it represents"
    return UnitFile(
        path=path,
        id=unit_id.strip(),
        covers=tuple(covers),
        source=str(meta.get("source") or ""),
        source_sha=str(meta.get("source_sha") or ""),
        body_sha=str(meta.get("body_sha") or ""),
        body=m.group(2),
    )


def read_unit_files(root: Path) -> tuple[list[UnitFile], list[str]]:
    directory = units_dir(root)
    if directory.exists() and not directory.is_dir():
        # Reported, not read as "no files": every unit would show as missing
        # and every stamp would report success while writing nothing.
        return [], [f"{UNITS_DIR} is not a directory — nothing can be digested"]
    if not directory.is_dir():
        return [], []
    files, problems = [], []
    for path in sorted(directory.glob("*.md")):
        read = read_unit_file(path)
        (problems if isinstance(read, str) else files).append(read)
    return files, problems


def stamp(unit_file: UnitFile, units: dict[str, Unit]) -> UnitFile | str:
    """Record the hashes on a unit file just written. Refused when it covers a
    unit the spec does not have, because a hash of nothing proves nothing."""
    missing = [c for c in unit_file.covers if c not in units]
    if missing:
        return (
            f"{unit_file.path.name}: covers {', '.join(missing)}, which the spec "
            "does not have — fix `covers` before stamping"
        )
    source_sha = covers_hash(units, unit_file.covers)
    assert source_sha is not None
    body_sha = file_hash(unit_file)
    write_atomic(
        unit_file.path,
        render_unit_file(
            unit_file.id,
            unit_file.covers,
            unit_file.source,
            source_sha,
            body_sha,
            unit_file.body,
        ),
    )
    return UnitFile(
        unit_file.path,
        unit_file.id,
        unit_file.covers,
        unit_file.source,
        source_sha,
        body_sha,
        unit_file.body,
    )


def digest_status(
    root: Path, units: dict[str, Unit], kinds: dict[str, str]
) -> DigestStatus:
    """Every derived unit file checked against the spec as it is now."""
    files, problems = read_unit_files(root)
    status = DigestStatus(unreadable=problems, files=len(files))
    covered: set[str] = set()
    covered_by: dict[str, list[str]] = {}
    seen_ids: dict[str, Path] = {}
    for f in files:
        name = f.path.name
        if f.id in seen_ids:
            status.unreadable.append(
                f"{name}: id '{f.id}' is already used by {seen_ids[f.id].name}"
            )
            continue
        seen_ids[f.id] = f.path
        covered.update(f.covers)
        for c in f.covers:
            covered_by.setdefault(c, []).append(name)
        missing = [c for c in f.covers if c not in units]
        if missing:
            status.removed.append(
                f"{name}: covers {', '.join(missing)}, no longer in the spec"
            )
            continue
        if not f.source_sha or not f.body_sha:
            status.unstamped.append(name)
            continue
        if file_hash(f) != f.body_sha:
            # Reported once, by its cause. A hand-edited `covers` also fails
            # the source check, and "the spec changed under it" would send a
            # session to re-derive a unit from a source that never moved.
            status.tampered.append(name)
            continue
        if covers_hash(units, f.covers) != f.source_sha:
            status.stale.append(name)
    status.new = [
        uid for uid in units if uid not in covered and kinds.get(uid) != INDEX
    ]
    status.overlapping = [
        f"{uid}: covered by {', '.join(sorted(names))}"
        for uid, names in sorted(covered_by.items())
        if len(names) > 1
    ]
    return status
